// GENERATED by Scripts/build_reading_test.py. Do not edit by hand: rerun the script.
//
// The Reading Test's word bank. Every Quranic word here was cut from the app's own Hafs text, read
// by a strict rule-based reader, and kept only where that reading agrees with the word-by-word
// transliteration the app ships. The unmarked words are kept only where their bare spelling is
// attested in the hadith corpus. See the script's module doc for the rules and the reading scheme.
//
// Words carry the mushaf's own marks: U+06E1 is the sukoon and U+0652 the "never read" circle.
// `ReadingTestText` turns them into whichever sukoon the reader has chosen before they are drawn.

import Foundation

enum ArabicReadingBank {
    /// tier | word | reading | reading when stopped on | surah:ayah | gloss of that occurrence |
    /// the word sounded out, as "letters=reading" groups (empty for the Name, which no rule reads)
    static let words = """
    spaced|هُوَ|huwa|huw|2:29|He|هُ=hu وَ=wa
    spaced|وَهُوَ|wahuwa|wahuw|2:29|And He|وَ=wa هُ=hu وَ=wa
    spaced|لَكَ|laka|lak|2:30|[to] You|لَ=la كَ=ka
    spaced|خَلَقَ|khalaqa|khalaq|2:29|created|خَ=kha لَ=la قَ=qa
    spaced|مَعَ|maʿa|maʿ|2:43|with|مَ=ma عَ=ʿa
    spaced|هِيَ|hiya|hiy|2:68|it (is)|هِ=hi يَ=ya
    spaced|جَعَلَ|jaʿala|jaʿal|2:22|made|جَ=ja عَ=ʿa لَ=la
    spaced|تَرَ|tara|tar|2:243|you see|تَ=ta رَ=ra
    spaced|فَهُوَ|fahuwa|fahuw|2:184|then it|فَ=fa هُ=hu وَ=wa
    spaced|كَفَرَ|kafara|kafar|2:102|disbelieved|كَ=ka فَ=fa رَ=ra
    spaced|لَهُوَ|lahuwa|lahuw|3:62|surely it (is)|لَ=la هُ=hu وَ=wa
    spaced|لِمَ|lima|lim|3:65|Why|لِ=li مَ=ma
    spaced|كُتِبَ|kutiba|kutib|2:178|Prescribed|كُ=ku تِ=ti بَ=ba
    spaced|تَرَكَ|taraka|tarak|2:180|he leaves|تَ=ta رَ=ra كَ=ka
    spaced|تَجِدَ|tajida|tajid|4:52|will you find|تَ=ta جِ=ji دَ=da
    spaced|بِكَ|bika|bik|3:36|in You|بِ=bi كَ=ka
    spaced|وَهِيَ|wahiya|wahiy|2:259|and it|وَ=wa هِ=hi يَ=ya
    spaced|مَثَلُ|mathalu|mathal|3:117|Example|مَ=ma ثَ=tha لُ=lu
    spaced|وَعَدَ|waʿada|waʿad|4:95|promised|وَ=wa عَ=ʿa دَ=da
    spaced|عَلِمَ|ʿalima|ʿalim|2:60|knew|عَ=ʿa لِ=li مَ=ma
    spaced|أَخَذَ|akhadha|akhadh|3:81|took|أَ=a خَ=kha ذَ=dha
    spaced|بَلَغَ|balagha|balagh|6:19|it reaches|بَ=ba لَ=la غَ=gha
    spaced|يَكُ|yaku|yak|8:53|is|يَ=ya كُ=ku
    spaced|كَتَبَ|kataba|katab|2:187|has ordained|كَ=ka تَ=ta بَ=ba
    spaced|عَمِلَ|ʿamila|ʿamil|6:54|does|عَ=ʿa مِ=mi لَ=la
    spaced|مَعِيَ|maʿiya|maʿiy|7:105|with me|مَ=ma عِ=ʿi يَ=ya
    spaced|كَرِهَ|kariha|karih|8:8|disliked (it)|كَ=ka رِ=ri هَ=ha
    spaced|تَكُ|taku|tak|4:40|there is|تَ=ta كُ=ku
    spaced|أَمَرَ|amara|amar|2:27|has ordered|أَ=a مَ=ma رَ=ra
    spaced|مَعَكَ|maʿaka|maʿak|4:102|with you|مَ=ma عَ=ʿa كَ=ka
    spaced|فَعَلَ|faʿala|faʿal|7:155|did|فَ=fa عَ=ʿa لَ=la
    spaced|تَجِدُ|tajidu|tajid|3:30|will find|تَ=ta جِ=ji دُ=du
    spaced|قُتِلَ|qutila|qutil|3:144|is slain|قُ=qu تِ=ti لَ=la
    spaced|يُطِعِ|yuTiʿi|yuTiʿ|4:13|obeys|يُ=yu طِ=Ti عِ=ʿi
    spaced|ذُكِرَ|dhukira|dhukir|6:118|(is) mentioned|ذُ=dhu كِ=ki رَ=ra
    spaced|قُضِيَ|quDiya|quDiy|10:47|it will be judged|قُ=qu ضِ=Di يَ=ya
    spaced|ضَرَبَ|Daraba|Darab|14:24|Allah sets forth|ضَ=Da رَ=ra بَ=ba
    spaced|ذَهَبَ|dhahaba|dhahab|2:17|took away|ذَ=dha هَ=ha بَ=ba
    spaced|فَهِيَ|fahiya|fahiy|2:74|so they|فَ=fa هِ=hi يَ=ya
    spaced|حَضَرَ|HaDara|HaDar|2:133|came to|حَ=Ha ضَ=Da رَ=ra
    vowels|وَهُوَ|wahuwa|wahuw|2:29|And He|وَ=wa هُ=hu وَ=wa
    vowels|خَلَقَ|khalaqa|khalaq|2:29|created|خَ=kha لَ=la قَ=qa
    vowels|جَعَلَ|jaʿala|jaʿal|2:22|made|جَ=ja عَ=ʿa لَ=la
    vowels|وَجَعَلَ|wajaʿala|wajaʿal|5:60|and made|وَ=wa جَ=ja عَ=ʿa لَ=la
    vowels|فَهُوَ|fahuwa|fahuw|2:184|then it|فَ=fa هُ=hu وَ=wa
    vowels|كَفَرَ|kafara|kafar|2:102|disbelieved|كَ=ka فَ=fa رَ=ra
    vowels|لَهُوَ|lahuwa|lahuw|3:62|surely it (is)|لَ=la هُ=hu وَ=wa
    vowels|كُتِبَ|kutiba|kutib|2:178|Prescribed|كُ=ku تِ=ti بَ=ba
    vowels|كَمَثَلِ|kamathali|kamathal|2:17|(is) like (the) example|كَ=ka مَ=ma ثَ=tha لِ=li
    vowels|تَرَكَ|taraka|tarak|2:180|he leaves|تَ=ta رَ=ra كَ=ka
    vowels|تَجِدَ|tajida|tajid|4:52|will you find|تَ=ta جِ=ji دَ=da
    vowels|وَعَمِلَ|waʿamila|waʿamil|2:62|and did|وَ=wa عَ=ʿa مِ=mi لَ=la
    vowels|وَهِيَ|wahiya|wahiy|2:259|and it|وَ=wa هِ=hi يَ=ya
    vowels|مَثَلُ|mathalu|mathal|3:117|Example|مَ=ma ثَ=tha لُ=lu
    vowels|وَعَدَ|waʿada|waʿad|4:95|promised|وَ=wa عَ=ʿa دَ=da
    vowels|عَلِمَ|ʿalima|ʿalim|2:60|knew|عَ=ʿa لِ=li مَ=ma
    vowels|أَخَذَ|akhadha|akhadh|3:81|took|أَ=a خَ=kha ذَ=dha
    vowels|بَلَغَ|balagha|balagh|6:19|it reaches|بَ=ba لَ=la غَ=gha
    vowels|كَتَبَ|kataba|katab|2:187|has ordained|كَ=ka تَ=ta بَ=ba
    vowels|عَمِلَ|ʿamila|ʿamil|6:54|does|عَ=ʿa مِ=mi لَ=la
    vowels|مَعِيَ|maʿiya|maʿiy|7:105|with me|مَ=ma عِ=ʿi يَ=ya
    vowels|كَرِهَ|kariha|karih|8:8|disliked (it)|كَ=ka رِ=ri هَ=ha
    vowels|أَمَرَ|amara|amar|2:27|has ordered|أَ=a مَ=ma رَ=ra
    vowels|مَعَكَ|maʿaka|maʿak|4:102|with you|مَ=ma عَ=ʿa كَ=ka
    vowels|فَعَلَ|faʿala|faʿal|7:155|did|فَ=fa عَ=ʿa لَ=la
    vowels|تَجِدُ|tajidu|tajid|3:30|will find|تَ=ta جِ=ji دُ=du
    vowels|قُتِلَ|qutila|qutil|3:144|is slain|قُ=qu تِ=ti لَ=la
    vowels|يُطِعِ|yuTiʿi|yuTiʿ|4:13|obeys|يُ=yu طِ=Ti عِ=ʿi
    vowels|ذُكِرَ|dhukira|dhukir|6:118|(is) mentioned|ذُ=dhu كِ=ki رَ=ra
    vowels|قُضِيَ|quDiya|quDiy|10:47|it will be judged|قُ=qu ضِ=Di يَ=ya
    vowels|ضَرَبَ|Daraba|Darab|14:24|Allah sets forth|ضَ=Da رَ=ra بَ=ba
    vowels|لَقُضِيَ|laquDiya|laquDiy|6:58|surely would have been decided|لَ=la قُ=qu ضِ=Di يَ=ya
    vowels|وَنُذُرِ|wanudhuri|wanudhur|54:16|and My warnings|وَ=wa نُ=nu ذُ=dhu رِ=ri
    vowels|ذَهَبَ|dhahaba|dhahab|2:17|took away|ذَ=dha هَ=ha بَ=ba
    vowels|فَهِيَ|fahiya|fahiy|2:74|so they|فَ=fa هِ=hi يَ=ya
    vowels|حَضَرَ|HaDara|HaDar|2:133|came to|حَ=Ha ضَ=Da رَ=ra
    vowels|سَلَفَ|salafa|salaf|2:275|(has) passed|سَ=sa لَ=la فَ=fa
    vowels|وَقَعَ|waqaʿa|waqaʿ|4:100|(became) incumbent|وَ=wa قَ=qa عَ=ʿa
    vowels|خَسِرَ|khasira|khasir|4:119|he (has) lost|خَ=kha سِ=si رَ=ra
    vowels|يَدَكَ|yadaka|yadak|5:28|your hand|يَ=ya دَ=da كَ=ka
    vowels|كَبُرَ|kabura|kabur|6:35|difficult|كَ=ka بُ=bu رَ=ra
    vowels|تَزِرُ|taziru|tazir|6:164|bears|تَ=ta زِ=zi رُ=ru
    vowels|أَذِنَ|adhina|adhin|10:59|permitted|أَ=a ذِ=dhi نَ=na
    vowels|جَرَمَ|jarama|jaram|11:22|doubt|جَ=ja رَ=ra مَ=ma
    vowels|وَقُضِيَ|waquDiya|waquDiy|2:210|and is decreed|وَ=wa قُ=qu ضِ=Di يَ=ya
    vowels|وَخَلَقَ|wakhalaqa|wakhalaq|4:1|and created|وَ=wa خَ=kha لَ=la قَ=qa
    vowels|كَلِمَتُ|kalimatu|kalimat|6:115|(the) word|كَ=ka لِ=li مَ=ma تُ=tu
    vowels|فَلِمَ|falima|falim|2:91|Then why|فَ=fa لِ=li مَ=ma
    tanween|أَبَدًا|abadan|abadaa|2:95|ever|أَ=a بَ=ba دًا=dan
    tanween|إِذًا|idhan|idhaa|2:145|(would) then|إِ=i ذًا=dhan
    tanween|أَحَدًا|aHadan|aHadaa|5:20|(to) anyone|أَ=a حَ=Ha دًا=dan
    tanween|حَسَنًا|Hasanan|Hasanaa|2:245|good|حَ=Ha سَ=sa نًا=nan
    tanween|مَثَلًا|mathalan|mathalaa|2:26|an example|مَ=ma ثَ=tha لًا=lan
    tanween|أَحَدٍ|aHadin|aHad|2:102|one|أَ=a حَ=Ha دٍ=din
    tanween|أَجَلٍ|ajalin|ajal|2:282|a term|أَ=a جَ=ja لٍ=lin
    tanween|بَشَرٌ|basharun|bashar|3:47|any man|بَ=ba شَ=sha رٌ=run
    tanween|كَذِبًا|kadhiban|kadhibaa|6:21|a lie|كَ=ka ذِ=dhi بًا=ban
    tanween|أَحَدٌ|aHadun|aHad|3:73|(to) one|أَ=a حَ=Ha دٌ=dun
    tanween|وَلَدًا|waladan|waladaa|2:116|a son|وَ=wa لَ=la دًا=dan
    tanween|وَلَدٌ|waladun|walad|3:47|a boy|وَ=wa لَ=la دٌ=dun
    tanween|هُزُوًا|huzuwan|huzuwaa|2:67|(in) ridicule|هُ=hu زُ=zu وًا=wan
    tanween|حَرَجٌ|Harajun|Haraj|7:2|any uneasiness|حَ=Ha رَ=ra جٌ=jun
    tanween|ثَمَنًا|thamanan|thamanaa|2:41|a price|ثَ=tha مَ=ma نًا=nan
    tanween|بَشَرًا|basharan|basharaa|11:27|a man|بَ=ba شَ=sha رًا=ran
    tanween|رَجُلٌ|rajulun|rajul|4:12|a man|رَ=ra جُ=ju لٌ=lun
    tanween|حَسَنَةً|Hasanatan|Hasanah|2:201|good|حَ=Ha سَ=sa نَ=na ةً=tan
    tanween|حَسَنَةٌ|Hasanatun|Hasanah|3:120|a good|حَ=Ha سَ=sa نَ=na ةٌ=tun
    tanween|عَمَلًا|ʿamalan|ʿamalaa|9:102|a deed|عَ=ʿa مَ=ma لًا=lan
    tanween|رُسُلٌ|rusulun|rusul|3:183|Messengers|رُ=ru سُ=su لٌ=lun
    tanween|رُسُلًا|rusulan|rusulaa|5:70|Messengers|رُ=ru سُ=su لًا=lan
    tanween|مَلَكٌ|malakun|malak|6:8|an Angel|مَ=ma لَ=la كٌ=kun
    tanween|أُمَمٍ|umamin|umam|6:42|nations|أُ=u مَ=ma مٍ=min
    tanween|عِوَجًا|ʿiwajan|ʿiwajaa|3:99|(seem) crooked|عِ=ʿi وَ=wa جًا=jan
    tanween|رَقَبَةٍ|raqabatin|raqabah|4:92|(of) a slave|رَ=ra قَ=qa بَ=ba ةٍ=tin
    tanween|رَجُلًا|rajulan|rajulaa|6:9|a man|رَ=ra جُ=ju لًا=lan
    tanween|كَلِمَةٌ|kalimatun|kalimah|10:19|a word|كَ=ka لِ=li مَ=ma ةٌ=tun
    tanween|سَنَةٍ|sanatin|sanah|2:96|year(s)|سَ=sa نَ=na ةٍ=tin
    tanween|سَفَرٍ|safarin|safar|2:184|a journey|سَ=sa فَ=fa رٍ=rin
    tanween|ذَكَرٍ|dhakarin|dhakar|3:195|(whether) male|ذَ=dha كَ=ka رٍ=rin
    tanween|رَجُلٍ|rajulin|rajul|7:63|a man|رَ=ra جُ=ju لٍ=lin
    tanween|ذَهَبٍ|dhahabin|dhahab|18:31|gold|ذَ=dha هَ=ha بٍ=bin
    tanween|نُزُلًا|nuzulan|nuzulaa|3:198|a hospitality|نُ=nu زُ=zu لًا=lan
    tanween|بِقَدَرٍ|biqadarin|biqadar|15:21|in a measure|بِ=bi قَ=qa دَ=da رٍ=rin
    tanween|رَشَدًا|rashadan|rashadaa|18:10|(in the) right way|رَ=ra شَ=sha دًا=dan
    tanween|أَجَلٌ|ajalun|ajal|6:60|(the) term|أَ=a جَ=ja لٌ=lun
    tanween|غَضَبٌ|ghaDabun|ghaDab|7:152|wrath|غَ=gha ضَ=Da بٌ=bun
    tanween|غَدًا|ghadan|ghadaa|12:12|tomorrow|غَ=gha دًا=dan
    tanween|سُرُرٍ|sururin|surur|15:47|thrones|سُ=su رُ=ru رٍ=rin
    long|فِي|fii|fii|2:10|In|فِي=fii
    long|مَا|maa|maa|2:17|what|مَا=maa
    long|لَا|laa|laa|2:2|no|لَا=laa
    long|وَلَا|walaa|walaa|1:7|and not|وَ=wa لَا=laa
    long|وَمَا|wamaa|wamaa|2:8|but not|وَ=wa مَا=maa
    long|قَالَ|qaala|qaal|2:30|said|قَا=qaa لَ=la
    long|كَانَ|kaana|kaan|2:75|(there) has been|كَا=kaa نَ=na
    long|بِمَا|bimaa|bimaa|2:10|because|بِ=bi مَا=maa
    long|فِيهَا|fiihaa|fiihaa|2:25|therein|فِي=fii هَا=haa
    long|إِذَا|idhaa|idhaa|2:177|when|إِ=i ذَا=dhaa
    long|فَلَا|falaa|falaa|2:22|So (do) not|فَ=fa لَا=laa
    long|عَلِيمٌ|ʿaliimun|ʿaliim|2:29|(is) All-Knowing|عَ=ʿa لِي=lii مٌ=mun
    long|وَقَالَ|waqaala|waqaal|2:118|And said|وَ=wa قَا=qaa لَ=la
    long|وَكَانَ|wakaana|wakaan|2:34|and became|وَ=wa كَا=kaa نَ=na
    long|دُونِ|duuni|duun|2:23|other than|دُو=duu نِ=ni
    long|عَذَابٌ|ʿadhaabun|ʿadhaab|2:7|(is) a punishment|عَ=ʿa ذَا=dhaa بٌ=bun
    long|سَبِيلِ|sabiili|sabiil|2:154|(the) way|سَ=sa بِي=bii لِ=li
    long|فَمَا|famaa|famaa|2:16|So not|فَ=fa مَا=maa
    long|بِهَا|bihaa|bihaa|2:258|it|بِ=bi هَا=haa
    long|لَنَا|lanaa|lanaa|2:61|for us|لَ=la نَا=naa
    long|قَلِيلًا|qaliilan|qaliilaa|2:41|small|قَ=qa لِي=lii لًا=lan
    long|غَفُورٌ|ghafuurun|ghafuur|2:173|(is) Oft-Forgiving|غَ=gha فُو=fuu رٌ=run
    long|يَقُولُونَ|yaquuluuna|yaquuluun|2:79|they say|يَ=ya قُو=quu لُو=luu نَ=na
    long|جَمِيعًا|jamiiʿan|jamiiʿaa|2:29|all|جَ=ja مِي=mii عًا=ʿan
    long|كَثِيرًا|kathiiran|kathiiraa|2:26|many|كَ=ka ثِي=thii رًا=ran
    long|أَفَلَا|afalaa|afalaa|2:44|Then, will not|أَ=a فَ=fa لَا=laa
    long|كَمَا|kamaa|kamaa|2:108|as|كَ=ka مَا=maa
    long|لِي|lii|lii|2:152|to Me|لِي=lii
    long|أَلِيمٌ|aliimun|aliim|2:10|painful|أَ=a لِي=lii مٌ=mun
    long|يُرِيدُ|yuriidu|yuriid|2:185|Intends|يُ=yu رِي=rii دُ=du
    long|عَذَابًا|ʿadhaaban|ʿadhaabaa|3:56|(with) a punishment|عَ=ʿa ذَا=dhaa بًا=ban
    long|قَدِيرٌ|qadiirun|qadiir|2:20|All-Powerful|قَ=qa دِي=dii رٌ=run
    long|عَذَابَ|ʿadhaaba|ʿadhaab|2:201|(from the) punishment|عَ=ʿa ذَا=dhaa بَ=ba
    long|لَهَا|lahaa|lahaa|2:134|for it|لَ=la هَا=haa
    long|يَقُولُ|yaquulu|yaquul|2:8|say|يَ=ya قُو=quu لُ=lu
    long|حَكِيمٌ|Hakiimun|Hakiim|2:209|All-Wise|حَ=Ha كِي=kii مٌ=mun
    long|قِيلَ|qiila|qiil|2:11|it is said|قِي=qii لَ=la
    long|أَلَا|alaa|alaa|6:31|Unquestionably|أَ=a لَا=laa
    long|عَظِيمٌ|ʿaDhiimun|ʿaDhiim|2:7|great|عَ=ʿa ظِي=Dhii مٌ=mun
    long|سَبِيلًا|sabiilan|sabiilaa|3:97|(find) a way|سَ=sa بِي=bii لًا=lan
    long|لَفِي|lafii|lafii|2:176|(are) surely in|لَ=la فِي=fii
    long|فَقَالَ|faqaala|faqaal|2:31|then He said|فَ=fa قَا=qaa لَ=la
    long|بَصِيرٌ|baSiirun|baSiir|2:96|(is) All-Seer|بَ=ba صِي=Sii رٌ=run
    long|وَفِي|wafii|wafii|2:49|And in|وَ=wa فِي=fii
    long|ذُو|dhuu|dhuu|2:105|(is the) Possessor|ذُو=dhuu
    long|عَزِيزٌ|ʿaziizun|ʿaziiz|2:209|(is) All-Mighty|عَ=ʿa زِي=zii زٌ=zun
    long|خَبِيرٌ|khabiirun|khabiir|2:234|(is) All-Aware|خَ=kha بِي=bii رٌ=run
    long|نُوحٍ|nuuHin|nuuH|4:163|Nuh|نُو=nuu حٍ=Hin
    long|نَذِيرٌ|nadhiirun|nadhiir|7:184|a warner|نَ=na ذِي=dhii رٌ=run
    long|عَلِيمًا|ʿaliiman|ʿaliimaa|4:11|All-Knowing|عَ=ʿa لِي=lii مًا=man
    long|عَظِيمًا|ʿaDhiiman|ʿaDhiimaa|4:27|great|عَ=ʿa ظِي=Dhii مًا=man
    long|رَسُولٌ|rasuulun|rasuul|2:87|a Messenger|رَ=ra سُو=suu لٌ=lun
    long|سَمِيعٌ|samiiʿun|samiiʿ|2:181|(is) All-Hearing|سَ=sa مِي=mii عٌ=ʿun
    long|أَخَافُ|akhaafu|akhaaf|5:28|fear|أَ=a خَا=khaa فُ=fu
    long|شَهِيدًا|shahiidan|shahiidaa|2:143|a witness|شَ=sha هِي=hii دًا=dan
    long|غَفُورًا|ghafuuran|ghafuuraa|4:23|Oft-Forgiving|غَ=gha فُو=fuu رًا=ran
    small|عَلَىٰ|ʿalaa|ʿalaa|2:5|(are) on|عَ=ʿa لَىٰ=laa
    small|ذَٰلِكَ|dhaalika|dhaalik|2:2|That|ذَٰ=dhaa لِ=li كَ=ka
    small|بِهِۦ|bihii|bih|2:22|therewith|بِ=bi هِۦ=hii
    small|إِلَىٰ|ilaa|ilaa|2:14|with|إِ=i لَىٰ=laa
    small|لَهُۥ|lahuu|lah|2:102|for him|لَ=la هُۥ=huu
    small|هَٰذَا|haadhaa|haadhaa|2:25|This (is)|هَٰ=haa ذَا=dhaa
    small|كَذَٰلِكَ|kadhaalika|kadhaalik|2:73|Like this|كَ=ka ذَٰ=dhaa لِ=li كَ=ka
    small|مُوسَىٰ|muusaa|muusaa|2:54|Musa|مُو=muu سَىٰ=saa
    small|خَٰلِدِينَ|khaalidiina|khaalidiin|2:162|(Will) abide forever|خَٰ=khaa لِ=li دِي=dii نَ=na
    small|وَكَذَٰلِكَ|wakadhaalika|wakadhaalik|2:143|And thus|وَ=wa كَ=ka ذَٰ=dhaa لِ=li كَ=ka
    small|إِلَٰهَ|ilaaha|ilaah|2:163|god|إِ=i لَٰ=laa هَ=ha
    small|صَٰلِحًا|SaaliHan|SaaliHaa|2:62|righteous deeds|صَٰ=Saa لِ=li حًا=Han
    small|صَٰدِقِينَ|Saadiqiina|Saadiqiin|2:23|truthful|صَٰ=Saa دِ=di قِي=qii نَ=na
    small|هُدًى|hudan|hudaa|2:2|a Guidance|هُ=hu دًى=dan
    small|ضَلَٰلٍ|Dalaalin|Dalaal|3:164|(the) error|ضَ=Da لَٰ=laa لٍ=lin
    small|عَٰقِبَةُ|ʿaaqibatu|ʿaaqibah|3:137|(the) end|عَٰ=ʿaa قِ=qi بَ=ba ةُ=tu
    small|خَٰلِدُونَ|khaaliduuna|khaaliduun|2:25|(will) abide forever|خَٰ=khaa لِ=li دُو=duu نَ=na
    small|دُونِهِۦ|duunihii|duunih|6:51|other than Him|دُو=duu نِ=ni هِۦ=hii
    small|مَعَهُۥ|maʿahuu|maʿah|2:214|with him|مَ=ma عَ=ʿa هُۥ=huu
    small|وَكَفَىٰ|wakafaa|wakafaa|4:6|And is sufficient|وَ=wa كَ=ka فَىٰ=faa
    small|صِرَٰطٍ|SiraaTin|SiraaT|2:142|a path|صِ=Si رَٰ=raa طٍ=Tin
    small|سَلَٰمٌ|salaamun|salaam|6:54|Peace|سَ=sa لَٰ=laa مٌ=mun
    small|بَلَىٰ|balaa|balaa|2:81|Yes|بَ=ba لَىٰ=laa
    small|إِلَٰهٌ|ilaahun|ilaah|2:163|(is) God|إِ=i لَٰ=laa هٌ=hun
    small|وَٰحِدَةً|waaHidatan|waaHidah|2:213|single|وَٰ=waa حِ=Hi دَ=da ةً=tan
    small|عِبَادِهِۦ|ʿibaadihii|ʿibaadih|2:90|His servants|عِ=ʿi بَا=baa دِ=di هِۦ=hii
    small|كِتَٰبٌ|kitaabun|kitaab|2:89|a Book|كِ=ki تَٰ=taa بٌ=bun
    small|إِلَٰهًا|ilaahan|ilaahaa|2:133|God|إِ=i لَٰ=laa هًا=han
    small|هَٰذِهِۦ|haadhihii|haadhih|4:78|This|هَٰ=haa ذِ=dhi هِۦ=hii
    small|كِتَٰبٍ|kitaabin|kitaab|3:81|(the) Book|كِ=ki تَٰ=taa بٍ=bin
    small|وَهُدًى|wahudan|wahudaa|2:97|and a guidance|وَ=wa هُ=hu دًى=dan
    small|كَٰفِرُونَ|kaafiruuna|kaafiruun|7:45|disbelievers|كَٰ=kaa فِ=fi رُو=ruu نَ=na
    small|وَهَٰذَا|wahaadhaa|wahaadhaa|3:68|and this|وَ=wa هَٰ=haa ذَا=dhaa
    small|وَذَٰلِكَ|wadhaalika|wadhaalik|4:13|And that|وَ=wa ذَٰ=dhaa لِ=li كَ=ka
    small|وَٰحِدٌ|waaHidun|waaHid|2:163|one (only)|وَٰ=waa حِ=Hi دٌ=dun
    small|وَعَلَىٰ|waʿalaa|waʿalaa|2:7|and on|وَ=wa عَ=ʿa لَىٰ=laa
    small|بِهَٰذَا|bihaadhaa|bihaadhaa|2:26|by this|بِ=bi هَٰ=haa ذَا=dhaa
    small|كِتَٰبًا|kitaaban|kitaabaa|3:145|(at a) decree|كِ=ki تَٰ=taa بًا=ban
    small|يَٰمُوسَىٰ|yaamuusaa|yaamuusaa|2:55|O Musa|يَٰ=yaa مُو=muu سَىٰ=saa
    small|وَرُسُلِهِۦ|warusulihii|warusulih|2:98|and His Messengers|وَ=wa رُ=ru سُ=su لِ=li هِۦ=hii
    small|سَبِيلِهِۦ|sabiilihii|sabiilih|5:35|His way|سَ=sa بِي=bii لِ=li هِۦ=hii
    small|مَتَىٰ|mataa|mataa|2:214|When|مَ=ma تَىٰ=taa
    small|بِغَٰفِلٍ|bighaafilin|bighaafil|2:74|unaware|بِ=bi غَٰ=ghaa فِ=fi لٍ=lin
    small|هَٰرُونَ|haaruuna|haaruun|2:248|(of) Harun|هَٰ=haa رُو=ruu نَ=na
    small|رَوَٰسِيَ|rawaasiya|rawaasiy|13:3|firm mountains|رَ=ra وَٰ=waa سِ=si يَ=ya
    small|أَسَٰطِيرُ|asaaTiiru|asaaTiir|6:25|(the) tales|أَ=a سَٰ=saa طِي=Tii رُ=ru
    small|ظَٰلِمِينَ|Dhaalimiina|Dhaalimiin|7:5|wrongdoers|ظَٰ=Dhaa لِ=li مِي=mii نَ=na
    small|لَكَٰذِبُونَ|lakaadhibuuna|lakaadhibuun|6:28|certainly are liars|لَ=la كَٰ=kaa ذِ=dhi بُو=buu نَ=na
    leen|أَوۡ|aw|aw|2:19|Or|أَوۡ=aw
    leen|عَلَيۡهِ|ʿalayhi|ʿalayh|2:37|towards him|عَ=ʿa لَيۡ=lay هِ=hi
    leen|يَوۡمَ|yawma|yawm|2:113|(on the) Day|يَوۡ=yaw مَ=ma
    leen|وَلَوۡ|walaw|walaw|2:20|And if|وَ=wa لَوۡ=law
    leen|خَيۡرٌ|khayrun|khayr|2:54|(is) better|خَيۡ=khay رٌ=run
    leen|إِلَيۡهِ|ilayhi|ilayh|2:28|to Him|إِ=i لَيۡ=lay هِ=hi
    leen|إِلَيۡكَ|ilayka|ilayk|2:4|to you|إِ=i لَيۡ=lay كَ=ka
    leen|بَيۡنَ|bayna|bayn|2:66|(in) front|بَيۡ=bay نَ=na
    leen|كَيۡفَ|kayfa|kayf|2:28|How|كَيۡ=kay فَ=fa
    leen|لَوۡ|law|law|2:96|if|لَوۡ=law
    leen|عَلَيۡكَ|ʿalayka|ʿalayk|2:252|to you|عَ=ʿa لَيۡ=lay كَ=ka
    leen|وَيَوۡمَ|wayawma|wayawm|2:85|and (on the) Day|وَ=wa يَوۡ=yaw مَ=ma
    leen|عَلَيۡهَا|ʿalayhaa|ʿalayhaa|2:142|[on it]|عَ=ʿa لَيۡ=lay هَا=haa
    leen|بِغَيۡرِ|bighayri|bighayr|2:61|without (any)|بِ=bi غَيۡ=ghay رِ=ri
    leen|عَلَيۡنَا|ʿalaynaa|ʿalaynaa|2:70|to us|عَ=ʿa لَيۡ=lay نَا=naa
    leen|قَوۡمًا|qawman|qawmaa|3:86|a people|قَوۡ=qaw مًا=man
    leen|غَيۡرَ|ghayra|ghayr|2:59|other (than)|غَيۡ=ghay رَ=ra
    leen|لَيۡسَ|laysa|lays|2:198|Not is|لَيۡ=lay سَ=sa
    leen|يَٰقَوۡمِ|yaaqawmi|yaaqawm|2:54|O my people|يَٰ=yaa قَوۡ=qaw مِ=mi
    leen|خَيۡرًا|khayran|khayraa|2:158|good|خَيۡ=khay رًا=ran
    leen|يَوۡمِ|yawmi|yawm|1:4|(of the) Day|يَوۡ=yaw مِ=mi
    leen|حَيۡثُ|Haythu|Hayth|2:35|(from) wherever|حَيۡ=Hay ثُ=thu
    leen|قَوۡمٌ|qawmun|qawm|5:11|a people|قَوۡ=qaw مٌ=mun
    leen|فَسَوۡفَ|fasawfa|fasawf|4:30|then soon|فَ=fa سَوۡ=saw فَ=fa
    leen|قَوۡمٍ|qawmin|qawm|3:117|(of) a people|قَوۡ=qaw مٍ=min
    leen|بَيۡنَهُمَا|baynahumaa|baynahumaa|4:128|between themselves|بَيۡ=bay نَ=na هُ=hu مَا=maa
    leen|خَيۡرُ|khayru|khayr|3:54|(is the) best|خَيۡ=khay رُ=ru
    leen|غَيۡرُ|ghayru|ghayr|4:95|other than|غَيۡ=ghay رُ=ru
    leen|قَوۡلًا|qawlan|qawlaa|2:59|(the) word|قَوۡ=qaw لًا=lan
    leen|قَوۡمِهِۦ|qawmihii|qawmih|6:83|his people|قَوۡ=qaw مِ=mi هِۦ=hii
    leen|يَدَيۡهِ|yadayhi|yadayh|2:97|before it|يَ=ya دَيۡ=day هِ=hi
    leen|وَلَوۡلَا|walawlaa|walawlaa|2:251|And if not|وَ=wa لَوۡ=law لَا=laa
    leen|يَوۡمًا|yawman|yawmaa|2:48|a day|يَوۡ=yaw مًا=man
    leen|فَكَيۡفَ|fakayfa|fakayf|3:25|Then how (will it be)|فَ=fa كَيۡ=kay فَ=fa
    leen|إِلَيۡنَا|ilaynaa|ilaynaa|2:136|to us|إِ=i لَيۡ=lay نَا=naa
    leen|رَيۡبَ|rayba|rayb|2:2|doubt|رَيۡ=ray بَ=ba
    leen|لِقَوۡمٍ|liqawmin|liqawm|2:118|for people|لِ=li قَوۡ=qaw مٍ=min
    leen|خَوۡفٌ|khawfun|khawf|2:38|fear|خَوۡ=khaw فٌ=fun
    leen|أَيۡنَ|ayna|ayn|2:148|Wherever|أَيۡ=ay نَ=na
    leen|وَيۡلٌ|waylun|wayl|45:7|Woe|وَيۡ=way لٌ=lun
    sukoon|مِنۡ|min|min|2:74|from|مِنۡ=min
    sukoon|قُلۡ|qul|qul|2:80|Say|قُلۡ=qul
    sukoon|لَهُمۡ|lahum|lahum|2:11|to them|لَ=la هُمۡ=hum
    sukoon|لَكُمۡ|lakum|lakum|2:58|for you|لَ=la كُمۡ=kum
    sukoon|إِذۡ|idh|idh|2:131|When|إِذۡ=idh
    sukoon|هُمۡ|hum|hum|2:4|they|هُمۡ=hum
    sukoon|عَلَيۡهِمۡ|ʿalayhim|ʿalayhim|1:7|on them|عَ=ʿa لَيۡ=lay هِمۡ=him
    sukoon|وَلَقَدۡ|walaqad|walaqad|2:65|And indeed|وَ=wa لَ=la قَدۡ=qad
    sukoon|عَلَيۡكُمۡ|ʿalaykum|ʿalaykum|2:40|upon you|عَ=ʿa لَيۡ=lay كُمۡ=kum
    sukoon|قَدۡ|qad|qad|2:60|Indeed|قَدۡ=qad
    sukoon|وَهُمۡ|wahum|wahum|2:25|and they|وَ=wa هُمۡ=hum
    sukoon|أَمۡ|am|am|2:6|or|أَمۡ=am
    sukoon|بَلۡ|bal|bal|2:100|Nay|بَلۡ=bal
    sukoon|إِنۡ|in|in|2:228|if|إِنۡ=in
    sukoon|لَمۡ|lam|lam|2:6|not|لَمۡ=lam
    sukoon|تَعۡمَلُونَ|taʿmaluuna|taʿmaluun|2:74|you do|تَعۡ=taʿ مَ=ma لُو=luu نَ=na
    sukoon|بَعۡدِ|baʿdi|baʿd|2:27|after|بَعۡ=baʿ دِ=di
    sukoon|يَعۡلَمُونَ|yaʿlamuuna|yaʿlamuun|2:13|they know|يَعۡ=yaʿ لَ=la مُو=muu نَ=na
    sukoon|أَلَمۡ|alam|alam|2:33|Did not|أَ=a لَمۡ=lam
    sukoon|مَنۡ|man|man|2:62|who|مَنۡ=man
    sukoon|قَبۡلُ|qablu|qabl|2:25|before|قَبۡ=qab لُ=lu
    sukoon|مِنۡهُمۡ|minhum|minhum|2:150|among them|مِنۡ=min هُمۡ=hum
    sukoon|هَلۡ|hal|hal|2:210|Are|هَلۡ=hal
    sukoon|مِنۡهَا|minhaa|minhaa|2:25|therefrom|مِنۡ=min هَا=haa
    sukoon|أَنۡ|an|an|2:67|that|أَنۡ=an
    sukoon|بَعۡدَ|baʿda|baʿd|2:120|after|بَعۡ=baʿ دَ=da
    sukoon|يَعۡمَلُونَ|yaʿmaluuna|yaʿmaluun|2:96|they do|يَعۡ=yaʿ مَ=ma لُو=luu نَ=na
    sukoon|نَحۡنُ|naHnu|naHn|2:11|we|نَحۡ=naH نُ=nu
    sukoon|أَعۡلَمُ|aʿlamu|aʿlam|2:30|[I] know|أَعۡ=aʿ لَ=la مُ=mu
    sukoon|تَعۡلَمُونَ|taʿlamuuna|taʿlamuun|2:22|[you] know|تَعۡ=taʿ لَ=la مُو=muu نَ=na
    sukoon|مِنۡهُ|minhu|minh|2:60|from it|مِنۡ=min هُ=hu
    sukoon|عَنۡهُمۡ|ʿanhum|ʿanhum|3:10|[for] them|عَنۡ=ʿan هُمۡ=hum
    sukoon|فَقَدۡ|faqad|faqad|2:108|so certainly|فَ=fa قَدۡ=qad
    sukoon|تَجۡرِي|tajrii|tajrii|2:25|flow|تَجۡ=taj رِي=rii
    sukoon|فِرۡعَوۡنَ|firʿawna|firʿawn|2:49|(of) Firaun|فِرۡ=fir عَوۡ=ʿaw نَ=na
    sukoon|وَلَمۡ|walam|walam|2:247|and not|وَ=wa لَمۡ=lam
    sukoon|وَمَنۡ|waman|waman|2:114|And who|وَ=wa مَنۡ=man
    sukoon|بَيۡنَهُمۡ|baynahum|baynahum|2:113|between them|بَيۡ=bay نَ=na هُمۡ=hum
    sukoon|أَصۡحَٰبُ|aSHaabu|aSHaab|2:39|(are the) companions|أَصۡ=aS حَٰ=Haa بُ=bu
    sukoon|أَرۡسَلۡنَا|arsalnaa|arsalnaa|2:151|We sent|أَرۡ=ar سَلۡ=sal نَا=naa
    sukoon|وَقَدۡ|waqad|waqad|2:75|while indeed|وَ=wa قَدۡ=qad
    sukoon|وَلَهُمۡ|walahum|walahum|2:7|And for them|وَ=wa لَ=la هُمۡ=hum
    sukoon|يَهۡدِي|yahdii|yahdii|2:142|He guides|يَهۡ=yah دِي=dii
    sukoon|إِبۡرَٰهِيمَ|ibraahiima|ibraahiim|3:33|(of) Ibrahim|إِبۡ=ib رَٰ=raa هِي=hii مَ=ma
    sukoon|بَعۡضٍ|baʿDin|baʿD|2:76|some (others)|بَعۡ=baʿ ضٍ=Din
    sukoon|عَنۡهُ|ʿanhu|ʿanh|4:31|from [it]|عَنۡ=ʿan هُ=hu
    sukoon|وَجَعَلۡنَا|wajaʿalnaa|wajaʿalnaa|5:13|and We made|وَ=wa جَ=ja عَلۡ=ʿal نَا=naa
    sukoon|لَقَدۡ|laqad|laqad|3:164|Certainly|لَ=la قَدۡ=qad
    sukoon|أَوَلَمۡ|awalam|awalam|2:260|Have not|أَ=a وَ=wa لَمۡ=lam
    sukoon|عَنۡ|ʿan|ʿan|2:119|about|عَنۡ=ʿan
    sukoon|تَحۡتِهَا|taHtihaa|taHtihaa|2:25|under them|تَحۡ=taH تِ=ti هَا=haa
    sukoon|فَهُمۡ|fahum|fahum|2:18|so they|فَ=fa هُمۡ=hum
    sukoon|إِلَيۡهِمۡ|ilayhim|ilayhim|3:77|at them|إِ=i لَيۡ=lay هِمۡ=him
    sukoon|وَمِنۡ|wamin|wamin|2:149|And from|وَ=wa مِنۡ=min
    sukoon|عِلۡمٍ|ʿilmin|ʿilm|4:157|(any) knowledge|عِلۡ=ʿil مٍ=min
    sukoon|قَبۡلِهِمۡ|qablihim|qablihim|3:11|before them|قَبۡ=qab لِ=li هِمۡ=him
    sukoon|قَبۡلِكَ|qablika|qablik|2:4|before you|قَبۡ=qab لِ=li كَ=ka
    sukoon|مَرۡيَمَ|maryama|maryam|2:87|(of) Maryam|مَرۡ=mar يَ=ya مَ=ma
    sukoon|جَعَلۡنَا|jaʿalnaa|jaʿalnaa|2:125|We made|جَ=ja عَلۡ=ʿal نَا=naa
    sukoon|تِلۡكَ|tilka|tilk|2:111|That|تِلۡ=til كَ=ka
    sukoon|بِكُمۡ|bikum|bikum|2:282|for you|بِ=bi كُمۡ=kum
    sukoon|ذَٰلِكُمۡ|dhaalikum|dhaalikum|2:54|That|ذَٰ=dhaa لِ=li كُمۡ=kum
    sukoon|بِهِمۡ|bihim|bihim|2:15|at them|بِ=bi هِمۡ=him
    sukoon|قَبۡلِ|qabli|qabl|2:237|before|قَبۡ=qab لِ=li
    shaddah|إِنَّ|inna|inn|2:6|Indeed|إِ=i نَّ=nna
    shaddah|إِلَّا|illaa|illaa|2:26|except|إِ=i لَّا=llaa
    shaddah|ثُمَّ|thumma|thumm|2:28|then|ثُ=thu مَّ=mma
    shaddah|إِنَّهُۥ|innahuu|innah|2:37|Indeed He|إِ=i نَّ=nna هُۥ=huu
    shaddah|كُلِّ|kulli|kull|2:20|every|كُ=ku لِّ=lli
    shaddah|إِنَّا|innaa|innaa|2:14|Indeed, we|إِ=i نَّا=nnaa
    shaddah|أَنَّ|anna|ann|2:25|that|أَ=a نَّ=nna
    shaddah|حَتَّىٰ|Hattaa|Hattaa|2:55|until|حَ=Ha تَّىٰ=ttaa
    shaddah|إِنَّمَا|innamaa|innamaa|2:11|Only|إِ=i نَّ=nna مَا=maa
    shaddah|رَبِّ|rabbi|rabb|1:2|the Lord|رَ=ra بِّ=bbi
    shaddah|إِنِّي|innii|innii|2:30|Indeed, I (am)|إِ=i نِّي=nnii
    shaddah|رَبِّكَ|rabbika|rabbik|6:115|(of) your Lord|رَ=ra بِّ=bbi كَ=ka
    shaddah|فَلَمَّا|falammaa|falammaa|2:89|then when|فَ=fa لَ=la مَّا=mmaa
    shaddah|رَبِّي|rabbii|rabbii|3:51|(is) my Lord|رَ=ra بِّي=bbii
    shaddah|كُنَّا|kunnaa|kunnaa|4:97|We were|كُ=ku نَّا=nnaa
    shaddah|رَبِّهِمۡ|rabbihim|rabbihim|2:46|their Lord|رَ=ra بِّ=bbi هِمۡ=him
    shaddah|إِنَّهُمۡ|innahum|innahum|2:12|indeed they|إِ=i نَّ=nna هُمۡ=hum
    shaddah|جَهَنَّمَ|jahannama|jahannam|3:12|Hell|جَ=ja هَ=ha نَّ=nna مَ=ma
    shaddah|وَلَٰكِنَّ|walaakinna|walaakinn|2:102|[and] but|وَ=wa لَٰ=laa كِ=ki نَّ=nna
    shaddah|رَبَّكَ|rabbaka|rabbak|2:61|(to) your Lord|رَ=ra بَّ=bba كَ=ka
    shaddah|مِمَّا|mimmaa|mimmaa|2:36|from what|مِ=mi مَّا=mmaa
    shaddah|لَعَلَّكُمۡ|laʿallakum|laʿallakum|2:21|so that you may|لَ=la عَ=ʿa لَّ=lla كُمۡ=kum
    shaddah|لِلَّذِينَ|lilladhiina|lilladhiin|2:212|for those who|لِ=li لَّ=lla ذِي=dhii نَ=na
    shaddah|كُلَّ|kulla|kull|2:276|every|كُ=ku لَّ=lla
    shaddah|إِنَّكَ|innaka|innak|2:32|Indeed You|إِ=i نَّ=nna كَ=ka
    shaddah|عَمَّا|ʿammaa|ʿammaa|2:74|of what|عَ=ʿa مَّا=mmaa
    shaddah|أَلَّا|allaa|allaa|2:229|that not|أَ=a لَّا=llaa
    shaddah|رَبَّنَا|rabbanaa|rabbanaa|2:127|(saying), "Our Lord|رَ=ra بَّ=bba نَا=naa
    shaddah|يُحِبُّ|yuHibbu|yuHibb|2:190|like|يُ=yu حِ=Hi بُّ=bbu
    shaddah|جَنَّٰتٍ|jannaatin|jannaat|2:25|(will be) Gardens|جَ=ja نَّٰ=nnaa تٍ=tin
    shaddah|لَعَلَّهُمۡ|laʿallahum|laʿallahum|2:186|so that they may|لَ=la عَ=ʿa لَّ=lla هُمۡ=hum
    shaddah|بِكُلِّ|bikulli|bikull|2:29|of every|بِ=bi كُ=ku لِّ=lli
    shaddah|أَنَّهُمۡ|annahum|annahum|2:103|[that] they|أَ=a نَّ=nna هُمۡ=hum
    shaddah|رَبِّكُمَا|rabbikumaa|rabbikumaa|55:13|(of) your Lord|رَ=ra بِّ=bbi كُ=ku مَا=maa
    shaddah|تُكَذِّبَانِ|tukadhdhibaani|tukadhdhibaan|55:13|will you both deny|تُ=tu كَ=ka ذِّ=dhdhi بَا=baa نِ=ni
    shaddah|وَلَمَّا|walammaa|walammaa|2:89|And when|وَ=wa لَ=la مَّا=mmaa
    shaddah|إِلَيَّ|ilayya|ilayy|3:55|to Myself|إِ=i لَ=la يَّ=yya
    shaddah|أُمَّةٍ|ummatin|ummah|3:110|(of) people|أُ=u مَّ=mma ةٍ=tin
    shaddah|لَمَّا|lammaa|lammaa|6:5|when|لَ=la مَّا=mmaa
    shaddah|إِنَّكُمۡ|innakum|innakum|2:54|Indeed, you|إِ=i نَّ=nna كُمۡ=kum
    shaddah|رَبُّكُمۡ|rabbukum|rabbukum|6:54|your Lord|رَ=ra بُّ=bbu كُمۡ=kum
    shaddah|رَبِّهِۦ|rabbihii|rabbih|2:112|his Lord|رَ=ra بِّ=bbi هِۦ=hii
    shaddah|كَذَّبَ|kadhdhaba|kadhdhab|6:21|rejects|كَ=ka ذَّ=dhdha بَ=ba
    shaddah|عَدُوٌّ|ʿaduwwun|ʿaduww|2:36|(as) enemy|عَ=ʿa دُ=du وٌّ=wwun
    shaddah|تَتَّقُونَ|tattaquuna|tattaquun|2:21|become righteous|تَ=ta تَّ=tta قُو=quu نَ=na
    shaddah|ضَلَّ|Dalla|Dall|2:108|he went astray (from)|ضَ=Da لَّ=lla
    shaddah|رَبُّ|rabbu|rabb|6:164|(is) the Lord|رَ=ra بُّ=bbu
    shaddah|أَشَدُّ|ashaddu|ashadd|2:74|stronger|أَ=a شَ=sha دُّ=ddu
    shaddah|أَيَّامٍ|ayyaamin|ayyaam|2:184|days|أَ=a يَّا=yyaa مٍ=min
    shaddah|جَهَنَّمُ|jahannamu|jahannam|2:206|(is) Hell|جَ=ja هَ=ha نَّ=nna مُ=mu
    shaddah|يَتَّقُونَ|yattaquuna|yattaquun|2:187|(become) righteous|يَ=ya تَّ=tta قُو=quu نَ=na
    shaddah|حَرَّمَ|Harrama|Harram|2:173|He has forbidden|حَ=Ha رَّ=rra مَ=ma
    shaddah|حَقًّا|Haqqan|Haqqaa|2:180|a duty|حَ=Ha قًّا=qqan
    shaddah|أَنَّهُۥ|annahuu|annah|3:18|that [He]|أَ=a نَّ=nna هُۥ=huu
    shaddah|تَذَكَّرُونَ|tadhakkaruuna|tadhakkaruun|6:152|remember|تَ=ta ذَ=dha كَّ=kka رُو=ruu نَ=na
    shaddah|أَوَّلَ|awwala|awwal|2:41|(the) first|أَ=a وَّ=wwa لَ=la
    shaddah|رَبُّنَا|rabbunaa|rabbunaa|2:139|(is) our Lord|رَ=ra بُّ=bbu نَا=naa
    shaddah|وَكُنَّا|wakunnaa|wakunnaa|7:173|and we are|وَ=wa كُ=ku نَّا=nnaa
    shaddah|أَنَّىٰ|annaa|annaa|2:223|when|أَ=a نَّىٰ=nnaa
    shaddah|عَلَيَّ|ʿalayya|ʿalayy|4:72|[on] me|عَ=ʿa لَ=la يَّ=yya
    shaddah|رَبَّكُمۡ|rabbakum|rabbakum|7:55|your Lord|رَ=ra بَّ=bba كُمۡ=kum
    shaddah|حَقَّ|Haqqa|Haqq|2:121|(as it has the) right|حَ=Ha قَّ=qqa
    shaddah|شَكٍّ|shakkin|shakk|4:157|doubt|شَ=sha كٍّ=kkin
    shaddah|أُمَّةً|ummatan|ummah|2:128|a community|أُ=u مَّ=mma ةً=tan
    mixed|شَيۡءٍ|shay'in|shay'|2:20|thing|شَيۡ=shay ءٍ='in
    mixed|يَٰٓأَيُّهَا|yaaaa'ayyuhaa|yaaaa'ayyuhaa|2:21|O|يَٰٓ=yaaaa أَ='a يُّ=yyu هَا=haa
    mixed|وَإِذَا|wa'idhaa|wa'idhaa|2:11|And when|وَ=wa إِ='i ذَا=dhaa
    mixed|يَشَآءُ|yashaaaa'u|yashaaaa'|2:90|He wills|يَ=ya شَآ=shaaaa ءُ='u
    mixed|يُؤۡمِنُونَ|yu'minuuna|yu'minuun|2:3|believe|يُؤۡ=yu' مِ=mi نُو=nuu نَ=na
    mixed|وَإِنَّ|wa'inna|wa'inn|2:74|And indeed|وَ=wa إِ='i نَّ=nna
    mixed|فَإِذَا|fa'idhaa|fa'idhaa|2:200|Then when|فَ=fa إِ='i ذَا=dhaa
    mixed|فَإِنَّ|fa'inna|fa'inn|2:61|so indeed|فَ=fa إِ='i نَّ=nna
    mixed|وَإِذۡ|wa'idh|wa'idh|2:30|And when|وَ=wa إِذۡ='idh
    mixed|يَوۡمَئِذٍ|yawma'idhin|yawma'idh|3:167|that day|يَوۡ=yaw مَ=ma ئِ='i ذٍ=dhin
    mixed|جَآءَ|jaaaa'a|jaaaa'|4:43|came|جَآ=jaaaa ءَ='a
    mixed|شَآءَ|shaaaa'a|shaaaa'|2:20|had willed|شَآ=shaaaa ءَ='a
    mixed|وَأَنَّ|wa'anna|wa'ann|2:165|and [that]|وَ=wa أَ='a نَّ=nna
    mixed|هَٰٓؤُلَآءِ|haaaa'ulaaaa'i|haaaa'ulaaaa'|2:31|(of) these|هَٰٓ=haaaa ؤُ='u لَآ=laaaa ءِ='i
    mixed|إِسۡرَٰٓءِيلَ|israaaa'iila|israaaa'iil|2:40|(of) Israel|إِسۡ=is رَٰٓ=raaaa ءِي='ii لَ=la
    mixed|فَبِأَيِّ|fabi'ayyi|fabi'ayy|7:185|So in what|فَ=fa بِ=bi أَ='a يِّ=yyi
    mixed|ءَالَآءِ|aalaaaa'i|aalaaaa'|53:55|the Favors|ءَا=aa لَآ=laaaa ءِ='i
    mixed|بَنِيٓ|baniiii|baniiii|2:83|(from the) Children|بَ=ba نِيٓ=niiii
    mixed|ءَامَنَّا|aamannaa|aamannaa|2:8|We believed|ءَا=aa مَ=ma نَّا=nnaa
    mixed|وَإِنَّا|wa'innaa|wa'innaa|5:22|and indeed, we|وَ=wa إِ='i نَّا=nnaa
    mixed|فَإِنَّمَا|fa'innamaa|fa'innamaa|2:117|[so] only|فَ=fa إِ='i نَّ=nna مَا=maa
    mixed|أَوۡلِيَآءَ|awliyaaaa'a|awliyaaaa'|3:28|(as) allies|أَوۡ=aw لِ=li يَآ=yaaaa ءَ='a
    mixed|ءَامَنَ|aamana|aaman|2:13|believed|ءَا=aa مَ=ma نَ=na
    mixed|مَآءً|maaaa'an|maaaa'aa|2:22|water|مَآ=maaaa ءً='an
    mixed|وَأَمَّا|wa'ammaa|wa'ammaa|2:26|And as for|وَ=wa أَ='a مَّا=mmaa
    mixed|فَإِنۡ|fa'in|fa'in|2:137|So if|فَ=fa إِنۡ='in
    mixed|بِأَنَّهُمۡ|bi'annahum|bi'annahum|2:61|because they|بِ=bi أَ='a نَّ=nna هُمۡ=hum
    mixed|وَإِنَّهُۥ|wa'innahuu|wa'innah|2:130|and indeed he|وَ=wa إِ='i نَّ=nna هُۥ=huu
    mixed|بِإِذۡنِ|bi'idhni|bi'idhn|2:97|by (the) permission|بِ=bi إِذۡ='idh نِ=ni
    mixed|ءَايَةً|aayatan|aayah|2:259|a sign|ءَا=aa يَ=ya ةً=tan
    mixed|وَإِلَيۡهِ|wa'ilayhi|wa'ilayh|2:245|and to Him|وَ=wa إِ='i لَيۡ=lay هِ=hi
    mixed|فَأَمَّا|fa'ammaa|fa'ammaa|2:26|Then as for|فَ=fa أَ='a مَّا=mmaa
    mixed|ءَايَٰتِ|aayaati|aayaat|2:231|(the) Verses|ءَا=aa يَٰ=yaa تِ=ti
    mixed|ءَايَٰتِنَا|aayaatinaa|aayaatinaa|2:151|Our verses|ءَا=aa يَٰ=yaa تِ=ti نَا=naa
    mixed|وَإِنۡ|wa'in|wa'in|2:78|and not|وَ=wa إِنۡ='in
    mixed|ءَايَٰتِهِۦ|aayaatihii|aayaatih|2:73|His Signs|ءَا=aa يَٰ=yaa تِ=ti هِۦ=hii
    mixed|يُؤۡمِنُ|yu'minu|yu'min|2:232|believes|يُؤۡ=yu' مِ=mi نُ=nu
    mixed|ءَاتَيۡنَا|aataynaa|aataynaa|2:53|We gave|ءَا=aa تَيۡ=tay نَا=naa
    mixed|وَبِئۡسَ|wabi'sa|wabi's|2:126|and evil|وَ=wa بِئۡ=bi' سَ=sa
    mixed|جَزَآءً|jazaaaa'an|jazaaaa'aa|5:38|(as) a recompense|جَ=ja زَآ=zaaaa ءً='an
    mixed|جَآءَهُمۡ|jaaaa'ahum|jaaaa'ahum|2:89|came to them|جَآ=jaaaa ءَ='a هُمۡ=hum
    mixed|بِأَنَّ|bi'anna|bi'ann|2:176|(is) because|بِ=bi أَ='a نَّ=nna
    mixed|يَأۡتِيَ|ya'tiya|ya'tiy|2:109|brings|يَأۡ=ya' تِ=ti يَ=ya
    mixed|فَإِنَّهُۥ|fa'innahuu|fa'innah|2:97|then indeed he|فَ=fa إِ='i نَّ=nna هُۥ=huu
    mixed|أَوۡحَيۡنَآ|awHaynaaaa|awHaynaaaa|4:163|have revealed|أَوۡ=aw حَيۡ=Hay نَآ=naaaa
    mixed|يَسۡتَهۡزِءُونَ|yastahzi'uuna|yastahzi'uun|6:5|mock|يَسۡ=yas تَهۡ=tah زِ=zi ءُو='uu نَ=na
    mixed|ءَادَمَ|aadama|aadam|2:31|Adam|ءَا=aa دَ=da مَ=ma
    mixed|ءَايَٰتُ|aayaatu|aayaat|2:252|(are the) Verses|ءَا=aa يَٰ=yaa تُ=tu
    mixed|يَٰٓأَهۡلَ|yaaaa'ahla|yaaaa'ahl|3:64|O People|يَٰٓ=yaaaa أَهۡ='ah لَ=la
    mixed|ءَالِهَةً|aalihatan|aalihah|6:19|(there are) gods|ءَا=aa لِ=li هَ=ha ةً=tan
    mixed|ءَايَةٍ|aayatin|aayah|2:106|a sign|ءَا=aa يَ=ya ةٍ=tin
    mixed|دَآبَّةٍ|daaaabbatin|daaaabbah|2:164|moving creature|دَآ=daaaa بَّ=bba ةٍ=tin
    mixed|وَإِنِّي|wa'innii|wa'innii|3:36|And that I|وَ=wa إِ='i نِّي=nnii
    mixed|أَرَءَيۡتُمۡ|ara'aytum|ara'aytum|6:46|Have you seen|أَ=a رَ=ra ءَيۡ='ay تُمۡ=tum
    mixed|ءَالَ|aala|aal|2:50|(the) people|ءَا=aa لَ=la
    mixed|شَيۡءٌ|shay'un|shay'|2:178|anything|شَيۡ=shay ءٌ='un
    article|ٱللَّهِ|allaahi|allaah|1:1|(of) Allah|
    article|ٱلَّذِينَ|al-ladhiina|al-ladhiin|1:7|(of) those|ٱ=al- لَّ=la ذِي=dhii نَ=na
    article|ٱللَّهُ|allaahu|allaah|2:7|Allah|
    article|وَٱللَّهُ|wallaahu|wallaah|2:19|And Allah|
    article|ٱلۡأَرۡضِ|al-arDi|al-arD|2:11|the earth|ٱلۡ=al- أَرۡ=ar ضِ=Di
    article|ٱلَّذِي|al-ladhii|al-ladhii|2:17|(of) the one who|ٱ=al- لَّ=la ذِي=dhii
    article|ٱلسَّمَٰوَٰتِ|as-samaawaati|as-samaawaat|2:33|(of) the heavens|ٱل=as- سَّ=sa مَٰ=maa وَٰ=waa تِ=ti
    article|وَٱلَّذِينَ|wal-ladhiina|wal-ladhiin|2:4|And those who|وَٱ=wal- لَّ=la ذِي=dhii نَ=na
    article|بِٱللَّهِ|billaahi|billaah|2:8|in Allah|
    article|ٱلدُّنۡيَا|ad-dunyaa|ad-dunyaa|2:85|(of) the world|ٱل=ad- دُّنۡ=dun يَا=yaa
    article|وَٱلۡأَرۡضِ|wal-arDi|wal-arD|2:33|and the earth|وَٱلۡ=wal- أَرۡ=ar ضِ=Di
    article|لِلَّهِ|lillaahi|lillaah|1:2|(be) to Allah|
    article|ٱلنَّاسِ|an-naasi|an-naas|2:8|the people|ٱل=an- نَّا=naa سِ=si
    article|ٱلسَّمَآءِ|as-samaaaa'i|as-samaaaa'|2:19|the sky|ٱل=as- سَّ=sa مَآ=maaaa ءِ='i
    article|ٱلۡكِتَٰبَ|al-kitaaba|al-kitaab|2:44|the Book|ٱلۡ=al- كِ=ki تَٰ=taa بَ=ba
    article|ٱلۡمُؤۡمِنِينَ|al-mu'miniina|al-mu'miniin|2:223|(to) the believers|ٱلۡ=al- مُؤۡ=mu' مِ=mi نِي=nii نَ=na
    article|ٱلۡكِتَٰبِ|al-kitaabi|al-kitaab|2:85|the Book|ٱلۡ=al- كِ=ki تَٰ=taa بِ=bi
    article|بِٱلۡحَقِّ|bil-Haqqi|bil-Haqq|2:71|with the truth|بِٱلۡ=bil- حَ=Ha قِّ=qqi
    article|ٱلنَّارِ|an-naari|an-naar|2:39|(of) the Fire|ٱل=an- نَّا=naa رِ=ri
    article|ٱلۡقِيَٰمَةِ|al-qiyaamati|al-qiyaamah|2:85|of [the] Resurrection|ٱلۡ=al- قِ=qi يَٰ=yaa مَ=ma ةِ=ti
    article|ٱلظَّٰلِمِينَ|aDh-Dhaalimiina|aDh-Dhaalimiin|2:35|the wrongdoers|ٱل=aDh- ظَّٰ=Dhaa لِ=li مِي=mii نَ=na
    article|ٱلۡعَٰلَمِينَ|al-ʿaalamiina|al-ʿaalamiin|1:2|of the universe|ٱلۡ=al- عَٰ=ʿaa لَ=la مِي=mii نَ=na
    article|ٱلصَّٰلِحَٰتِ|aS-SaaliHaati|aS-SaaliHaat|2:25|[the] righteous deeds|ٱل=aS- صَّٰ=Saa لِ=li حَٰ=Haa تِ=ti
    article|ٱلۡكَٰفِرِينَ|al-kaafiriina|al-kaafiriin|2:34|the disbelievers|ٱلۡ=al- كَٰ=kaa فِ=fi رِي=rii نَ=na
    article|ٱلۡحَقُّ|al-Haqqu|al-Haqq|2:26|(is) the truth|ٱلۡ=al- حَ=Ha قُّ=qqu
    article|ٱلنَّاسَ|an-naasa|an-naas|2:44|[the] people|ٱل=an- نَّا=naa سَ=sa
    article|ٱلۡعَزِيزُ|al-ʿaziizu|al-ʿaziiz|2:129|the All-Mighty|ٱلۡ=al- عَ=ʿa زِي=zii زُ=zu
    article|ٱلۡأَرۡضَ|al-arDa|al-arD|2:22|the earth|ٱلۡ=al- أَرۡ=ar ضَ=Da
    article|ٱلَّتِي|al-latii|al-latii|2:24|whose|ٱ=al- لَّ=la تِي=tii
    article|وَٱلۡأَرۡضَ|wal-arDa|wal-arD|2:255|and the earth|وَٱلۡ=wal- أَرۡ=ar ضَ=Da
    article|ٱلۡأَنۡهَٰرُ|al-anhaaru|al-anhaar|2:25|the rivers|ٱلۡ=al- أَنۡ=an هَٰ=haa رُ=ru
    article|ٱلۡيَوۡمَ|al-yawma|al-yawm|2:249|today|ٱلۡ=al- يَوۡ=yaw مَ=ma
    article|ٱلۡحَقِّ|al-Haqqi|al-Haqq|2:61|[the] right|ٱلۡ=al- حَ=Ha قِّ=qqi
    article|ٱلۡعَذَابِ|al-ʿadhaabi|al-ʿadhaab|2:49|torment|ٱلۡ=al- عَ=ʿa ذَا=dhaa بِ=bi
    article|ٱلشَّيۡطَٰنُ|ash-shayTaanu|ash-shayTaan|2:36|the Shaitaan|ٱل=ash- شَّيۡ=shay طَٰ=Taa نُ=nu
    article|ٱلۡحَكِيمُ|al-Hakiimu|al-Hakiim|2:32|the All-Wise|ٱلۡ=al- حَ=Ha كِي=kii مُ=mu
    article|ٱلۡقَوۡمِ|al-qawmi|al-qawm|2:250|the people|ٱلۡ=al- قَوۡ=qaw مِ=mi
    article|ٱلۡأَوَّلِينَ|al-awwaliina|al-awwaliin|6:25|(of) the former (people)|ٱلۡ=al- أَ=a وَّ=wwa لِي=lii نَ=na
    article|ٱلَّيۡلِ|al-layli|al-layl|2:164|of the night|ٱ=al- لَّيۡ=lay لِ=li
    article|ٱلۡمُحۡسِنِينَ|al-muHsiniina|al-muHsiniin|2:58|the good-doers (in reward)|ٱلۡ=al- مُحۡ=muH سِ=si نِي=nii نَ=na
    article|ٱلۡعَلِيمُ|al-ʿaliimu|al-ʿaliim|2:32|(are) the All-Knowing|ٱلۡ=al- عَ=ʿa لِي=lii مُ=mu
    article|ٱلرَّحِيمُ|ar-raHiimu|ar-raHiim|2:37|the Most Merciful|ٱل=ar- رَّ=ra حِي=Hii مُ=mu
    article|ٱلۡعَذَابَ|al-ʿadhaaba|al-ʿadhaab|2:165|the punishment|ٱلۡ=al- عَ=ʿa ذَا=dhaa بَ=ba
    article|ٱلدِّينِ|ad-diini|ad-diin|1:4|(of the) Judgment|ٱل=ad- دِّي=dii نِ=ni
    article|ٱلۡجَنَّةِ|al-jannati|al-jannah|2:82|(of) Paradise|ٱلۡ=al- جَ=ja نَّ=nna ةِ=ti
    article|ٱلۡحَمۡدُ|al-Hamdu|al-Hamd|1:2|All praises and thanks|ٱلۡ=al- حَمۡ=Ham دُ=du
    article|ٱلۡقَوۡمَ|al-qawma|al-qawm|2:258|the people|ٱلۡ=al- قَوۡ=qaw مَ=ma
    article|وَلِلَّهِ|walillaahi|walillaah|2:115|And for Allah|
    article|ٱلَّيۡلَ|al-layla|al-layl|3:27|the night|ٱ=al- لَّيۡ=lay لَ=la
    article|بِٱلۡبَيِّنَٰتِ|bil-bayyinaati|bil-bayyinaat|2:92|with [the] clear signs|بِٱلۡ=bil- بَ=ba يِّ=yyi نَٰ=naa تِ=ti
    article|ٱلظَّٰلِمُونَ|aDh-Dhaalimuuna|aDh-Dhaalimuun|2:229|(are) the wrongdoers|ٱل=aDh- ظَّٰ=Dhaa لِ=li مُو=muu نَ=na
    article|ٱلۡمُشۡرِكِينَ|al-mushrikiina|al-mushrikiin|2:105|those who associate partners (with Allah)|ٱلۡ=al- مُشۡ=mush رِ=ri كِي=kii نَ=na
    article|ٱلۡمُرۡسَلِينَ|al-mursaliina|al-mursaliin|2:252|the Messengers|ٱلۡ=al- مُرۡ=mur سَ=sa لِي=lii نَ=na
    article|ٱلۡمَصِيرُ|al-maSiiru|al-maSiir|2:126|(is) the destination|ٱلۡ=al- مَ=ma صِي=Sii رُ=ru
    article|ٱلۡمُتَّقِينَ|al-muttaqiina|al-muttaqiin|2:180|the righteous ones|ٱلۡ=al- مُ=mu تَّ=tta قِي=qii نَ=na
    article|ٱلۡقُرۡءَانَ|al-qur'aana|al-qur'aan|4:82|(on) the Quran|ٱلۡ=al- قُرۡ=qur ءَا='aa نَ=na
    article|ٱلۡمُؤۡمِنُونَ|al-mu'minuuna|al-mu'minuun|3:28|the believers|ٱلۡ=al- مُؤۡ=mu' مِ=mi نُو=nuu نَ=na
    article|ٱلنَّارُ|an-naaru|an-naar|2:80|the Fire|ٱل=an- نَّا=naa رُ=ru
    article|ٱلرَّحۡمَٰنِ|ar-raHmaani|ar-raHmaan|1:1|the Most Gracious|ٱل=ar- رَّحۡ=raH مَٰ=maa نِ=ni
    article|وَٱلۡيَوۡمِ|wal-yawmi|wal-yawm|2:62|and the Day|وَٱلۡ=wal- يَوۡ=yaw مِ=mi
    article|ٱلرَّحۡمَٰنُ|ar-raHmaanu|ar-raHmaan|2:163|the Most Gracious|ٱل=ar- رَّحۡ=raH مَٰ=maa نُ=nu
    article|ٱلۡمَلَٰٓئِكَةُ|al-malaaaa'ikatu|al-malaaaa'ikah|2:248|the Angels|ٱلۡ=al- مَ=ma لَٰٓ=laaaa ئِ='i كَ=ka ةُ=tu
    article|ٱلسَّبِيلِ|as-sabiili|as-sabiil|2:108|(of) the way|ٱل=as- سَّ=sa بِي=bii لِ=li
    article|بِٱلۡمَعۡرُوفِ|bil-maʿruufi|bil-maʿruuf|2:178|with suitable|بِٱلۡ=bil- مَعۡ=maʿ رُو=ruu فِ=fi
    wasl|وَٱتَّقُواْ|wattaquu|wattaquu|2:48|And fear|وَٱ=wa تَّ=tta قُواْ=quu
    wasl|وَٱعۡلَمُوٓاْ|waʿlamuuuu|waʿlamuuuu|2:194|and know|وَٱعۡ=waʿ لَ=la مُوٓاْ=muuuu
    wasl|ٱعۡبُدُواْ|uʿbuduu|uʿbuduu|2:21|worship|ٱعۡ=uʿ بُ=bu دُواْ=duu
    wasl|فَٱتَّقُواْ|fattaquu|fattaquu|2:24|then fear|فَٱ=fa تَّ=tta قُواْ=quu
    wasl|ٱتَّخَذُواْ|ittakhadhuu|ittakhadhuu|4:153|they took|ٱ=i تَّ=tta خَ=kha ذُواْ=dhuu
    wasl|ٱتَّخَذَ|ittakhadha|ittakhadh|2:116|has taken|ٱ=i تَّ=tta خَ=kha ذَ=dha
    wasl|ٱتَّقُواْ|ittaquu|ittaquu|2:278|Fear|ٱ=i تَّ=tta قُواْ=quu
    wasl|ٱفۡتَرَىٰ|iftaraa|iftaraa|3:94|fabricates|ٱفۡ=if تَ=ta رَىٰ=raa
    wasl|ٱبۡنُ|ibnu|ibn|3:45|son|ٱبۡ=ib نُ=nu
    wasl|فَٱصۡبِرۡ|faSbir|faSbir|11:49|So be patient|فَٱصۡ=faS بِرۡ=bir
    wasl|ٱدۡخُلُواْ|udkhuluu|udkhuluu|2:58|Enter|ٱدۡ=ud خُ=khu لُواْ=luu
    wasl|ٱبۡنَ|ibna|ibn|2:87|(the) son|ٱبۡ=ib نَ=na
    wasl|ٱثۡنَيۡنِ|ithnayni|ithnayn|6:143|two|ٱثۡ=ith نَيۡ=nay نِ=ni
    wasl|وَٱذۡكُرۡ|wadhkur|wadhkur|19:16|And mention|وَٱذۡ=wadh كُرۡ=kur
    wasl|ٱبۡتِغَآءَ|ibtighaaaa'a|ibtighaaaa'|2:207|seeking|ٱبۡ=ib تِ=ti غَآ=ghaaaa ءَ='a
    wasl|ٱسۡمَ|isma|ism|5:4|(the) name|ٱسۡ=is مَ=ma
    wasl|ٱتَّقَوۡاْ|ittaqaw|ittaqaw|2:212|fear (Allah)|ٱ=i تَّ=tta قَوۡاْ=qaw
    wasl|ٱذۡكُرُواْ|udhkuruu|udhkuruu|2:40|Remember|ٱذۡ=udh كُ=ku رُواْ=ruu
    wasl|وَٱذۡكُرُواْ|wadhkuruu|wadhkuruu|2:63|and remember|وَٱذۡ=wadh كُ=ku رُواْ=ruu
    wasl|ٱتَّبَعَ|ittabaʿa|ittabaʿ|3:162|pursues|ٱ=i تَّ=tta بَ=ba عَ=ʿa
    wasl|ٱخۡتَلَفُواْ|ikhtalafuu|ikhtalafuu|2:176|who differed|ٱخۡ=ikh تَ=ta لَ=la فُواْ=fuu
    wasl|ٱغۡفِرۡ|ighfir|ighfir|3:147|forgive|ٱغۡ=igh فِرۡ=fir
    wasl|ٱسۡتَوَىٰ|istawaa|istawaa|7:54|He ascended|ٱسۡ=is تَ=ta وَىٰ=waa
    wasl|ٱهۡتَدَىٰ|ihtadaa|ihtadaa|10:108|(is) guided|ٱهۡ=ih تَ=ta دَىٰ=daa
    wasl|وَٱصۡبِرۡ|waSbir|waSbir|10:109|and be patient|وَٱصۡ=waS بِرۡ=bir
    wasl|ٱفۡتَرَىٰهُ|iftaraahu|iftaraah|10:38|He has invented it|ٱفۡ=if تَ=ta رَىٰ=raa هُ=hu
    wasl|ٱسۡتَكۡبَرُواْ|istakbaruu|istakbaruu|7:75|(who) were arrogant|ٱسۡ=is تَكۡ=tak بَ=ba رُواْ=ruu
    wasl|ٱدۡعُ|udʿu|udʿ|2:68|Pray|ٱدۡ=ud عُ=ʿu
    wasl|فَٱغۡفِرۡ|faghfir|faghfir|3:16|so forgive|فَٱغۡ=fagh فِرۡ=fir
    wasl|ٱتَّبِعُواْ|ittabiʿuu|ittabiʿuu|2:170|Follow|ٱ=i تَّ=tta بِ=bi عُواْ=ʿuu
    wasl|ٱعۡمَلُواْ|iʿmaluu|iʿmaluu|6:135|Work|ٱعۡ=iʿ مَ=ma لُواْ=luu
    wasl|وَٱشۡرَبُواْ|washrabuu|washrabuu|2:60|and drink|وَٱشۡ=wash رَ=ra بُواْ=buu
    wasl|وَٱتَّبَعُواْ|wattabaʿuu|wattabaʿuu|2:102|And they followed|وَٱ=wa تَّ=tta بَ=ba عُواْ=ʿuu
    wasl|فَٱعۡلَمُوٓاْ|faʿlamuuuu|faʿlamuuuu|2:209|then know|فَٱعۡ=faʿ لَ=la مُوٓاْ=muuuu
    wasl|ٱسۡمُ|ismu|ism|6:118|(the) name|ٱسۡ=is مُ=mu
    wasl|وَٱبۡنِ|wabni|wabn|2:215|and (of)|وَٱبۡ=wab نِ=ni
    wasl|وَٱتۡلُ|watlu|watl|5:27|And recite|وَٱتۡ=wat لُ=lu
    wasl|وَٱتَّبَعَ|wattabaʿa|wattabaʿ|4:125|and follows|وَٱ=wa تَّ=tta بَ=ba عَ=ʿa
    wasl|ٱسۡجُدُواْ|usjuduu|usjuduu|2:34|Prostrate|ٱسۡ=us جُ=ju دُواْ=duu
    wasl|ٱتَّبَعُواْ|ittabaʿuu|ittabaʿuu|2:166|followed|ٱ=i تَّ=tta بَ=ba عُواْ=ʿuu
    wasl|وَٱشۡكُرُواْ|washkuruu|washkuruu|2:152|and be grateful|وَٱشۡ=wash كُ=ku رُواْ=ruu
    wasl|فَٱذۡكُرُواْ|fadhkuruu|fadhkuruu|2:198|then remember|فَٱذۡ=fadh كُ=ku رُواْ=ruu
    wasl|فَٱعۡبُدُوهُ|faʿbuduuhu|faʿbuduuh|3:51|so worship Him|فَٱعۡ=faʿ بُ=bu دُو=duu هُ=hu
    wasl|وَٱسۡتَغۡفِرۡ|wastaghfir|wastaghfir|3:159|and ask forgiveness|وَٱسۡ=was تَغۡ=tagh فِرۡ=fir
    wasl|فَٱسۡتَكۡبَرُواْ|fastakbaruu|fastakbaruu|7:133|but they showed arrogance|فَٱسۡ=fas تَكۡ=tak بَ=ba رُواْ=ruu
    wasl|ٱضۡطُرَّ|uDTurra|uDTurr|2:173|(is) forced by necessity|ٱضۡ=uD طُ=Tu رَّ=rra
    wasl|ٱتَّقَىٰ|ittaqaa|ittaqaa|2:189|fears (Allah)|ٱ=i تَّ=tta قَىٰ=qaa
    wasl|ٱذۡهَبۡ|idhhab|idhhab|17:63|Go|ٱذۡ=idh هَبۡ=hab
    silent|ءَامَنُواْ|aamanuu|aamanuu|2:9|believe[d]|ءَا=aa مَ=ma نُواْ=nuu
    silent|كَانُواْ|kaanuu|kaanuu|2:10|they used to|كَا=kaa نُواْ=nuu
    silent|قَالُواْ|qaaluu|qaaluu|2:25|they (will) say|قَا=qaa لُواْ=luu
    silent|كَفَرُواْ|kafaruu|kafaruu|2:6|disbelieve[d]|كَ=ka فَ=fa رُواْ=ruu
    silent|كُنتُمۡ|kuntum|kuntum|2:23|you are|كُن=kun تُمۡ=tum
    silent|أُوْلَٰٓئِكَ|ulaaaa'ika|ulaaaa'ik|2:5|Those|أُوْ=u لَٰٓ=laaaa ئِ='i كَ=ka
    silent|عِندَ|ʿinda|ʿind|2:54|with|عِن=ʿin دَ=da
    silent|مِنكُمۡ|minkum|minkum|2:65|among you|مِن=min كُمۡ=kum
    silent|أَنتَ|anta|ant|2:32|You|أَن=an تَ=ta
    silent|وَعَمِلُواْ|waʿamiluu|waʿamiluu|2:25|and do|وَ=wa عَ=ʿa مِ=mi لُواْ=luu
    silent|أَنتُمۡ|antum|antum|2:85|you|أَن=an تُمۡ=tum
    silent|وَقَالُواْ|waqaaluu|waqaaluu|2:80|And they say|وَ=wa قَا=qaa لُواْ=luu
    silent|أُنزِلَ|unzila|unzil|2:4|(is) sent down|أُن=un زِ=zi لَ=la
    silent|أَنزَلَ|anzala|anzal|2:90|has revealed|أَن=an زَ=za لَ=la
    silent|وَأَنتُمۡ|wa'antum|wa'antum|2:22|while you|وَ=wa أَن='an تُمۡ=tum
    silent|كَذَّبُواْ|kadhdhabuu|kadhdhabuu|3:11|They denied|كَ=ka ذَّ=dhdha بُواْ=buu
    silent|كُنتَ|kunta|kunt|2:143|you were used to|كُن=kun تَ=ta
    silent|أَنفُسَهُمۡ|anfusahum|anfusahum|2:9|themselves|أَن=an فُ=fu سَ=sa هُمۡ=hum
    silent|أُوتُواْ|uutuu|uutuu|2:101|were given|أُو=uu تُواْ=tuu
    silent|وَكَانُواْ|wakaanuu|wakaanuu|2:89|though they used to|وَ=wa كَا=kaa نُواْ=nuu
    silent|ظَلَمُواْ|Dhalamuu|Dhalamuu|2:59|wronged|ظَ=Dha لَ=la مُواْ=muu
    silent|ٱلۡإِنسَٰنُ|al-insaanu|al-insaan|4:28|the mankind|ٱلۡ=al- إِن=in سَٰ=saa نُ=nu
    silent|ٱلۡإِنسَٰنَ|al-insaana|al-insaan|10:12|the man|ٱلۡ=al- إِن=in سَٰ=saa نَ=na
    silent|يَرَوۡاْ|yaraw|yaraw|6:6|they see|يَ=ya رَوۡاْ=raw
    silent|أَنفُسِهِمۡ|anfusihim|anfusihim|2:265|their (inner) souls|أَن=an فُ=fu سِ=si هِمۡ=him
    silent|عِندِ|ʿindi|ʿind|2:79|from|عِن=ʿin دِ=di
    silent|يُنفِقُونَ|yunfiquuna|yunfiquun|2:3|they spend|يُن=yun فِ=fi قُو=quu نَ=na
    silent|تَوَلَّوۡاْ|tawallaw|tawallaw|2:137|they turn away|تَ=ta وَ=wa لَّوۡاْ=llaw
    silent|تَكُونُواْ|takuunuu|takuunuu|2:148|you will be|تَ=ta كُو=kuu نُواْ=nuu
    silent|يَنظُرُونَ|yanDhuruuna|yanDhuruun|2:210|they waiting|يَن=yan ظُ=Dhu رُو=ruu نَ=na
    silent|عَنكُمۡ|ʿankum|ʿankum|2:187|[on] you|عَن=ʿan كُمۡ=kum
    silent|عَمِلُواْ|ʿamiluu|ʿamiluu|6:132|they did|عَ=ʿa مِ=mi لُواْ=luu
    silent|أَنزَلۡنَا|anzalnaa|anzalnaa|2:159|We revealed|أَن=an زَلۡ=zal نَا=naa
    silent|كُنتُ|kuntu|kunt|4:73|I had been|كُن=kun تُ=tu
    silent|كُلُواْ|kuluu|kuluu|2:57|Eat|كُ=ku لُواْ=luu
    silent|وَأَنتَ|wa'anta|wa'ant|5:114|and You|وَ=wa أَن='an تَ=ta
    silent|كَسَبُواْ|kasabuu|kasabuu|2:202|they earned|كَ=ka سَ=sa بُواْ=buu
    silent|أَنفُسَكُمۡ|anfusakum|anfusakum|2:44|yourselves|أَن=an فُ=fu سَ=sa كُمۡ=kum
    silent|أَنفُسِكُمۡ|anfusikum|anfusikum|2:235|yourselves|أَن=an فُ=fu سِ=si كُمۡ=kum
    silent|أَنزَلۡنَٰهُ|anzalnaahu|anzalnaah|6:92|We have revealed it|أَن=an زَلۡ=zal نَٰ=naa هُ=hu
    silent|عِندَهُۥ|ʿindahuu|ʿindah|2:140|(that) he has|عِن=ʿin دَ=da هُۥ=huu
    silent|أُوْلُواْ|uluu|uluu|2:269|those|أُوْ=u لُواْ=luu
    silent|تَقُولُواْ|taquuluu|taquuluu|2:104|say|تَ=ta قُو=quu لُواْ=luu
    silent|وَأَطِيعُواْ|wa'aTiiʿuu|wa'aTiiʿuu|3:132|And obey|وَ=wa أَ='a طِي=Tii عُواْ=ʿuu
    silent|يَكُونُواْ|yakuunuu|yakuunuu|9:18|they are|يَ=ya كُو=kuu نُواْ=nuu
    silent|وَأَنزَلَ|wa'anzala|wa'anzal|2:22|and sent down|وَ=wa أَن='an زَ=za لَ=la
    silent|صَبَرُواْ|Sabaruu|Sabaruu|7:137|they were patient|صَ=Sa بَ=ba رُواْ=ruu
    silent|وَءَاتُواْ|wa'aatuu|wa'aatuu|2:43|and give|وَ=wa ءَا='aa تُواْ=tuu
    waqf|ٱلۡقِيَٰمَةِ|al-qiyaamati|al-qiyaamah|2:85|of [the] Resurrection|ٱلۡ=al- قِ=qi يَٰ=yaa مَ=ma ةِ=ti
    waqf|ٱلۡجَنَّةِ|al-jannati|al-jannah|2:82|(of) Paradise|ٱلۡ=al- جَ=ja نَّ=nna ةِ=ti
    waqf|عَٰقِبَةُ|ʿaaqibatu|ʿaaqibah|3:137|(the) end|عَٰ=ʿaa قِ=qi بَ=ba ةُ=tu
    waqf|أُمَّةٍ|ummatin|ummah|3:110|(of) people|أُ=u مَّ=mma ةٍ=tin
    waqf|ءَايَةً|aayatan|aayah|2:259|a sign|ءَا=aa يَ=ya ةً=tan
    waqf|ٱلۡمَلَٰٓئِكَةُ|al-malaaaa'ikatu|al-malaaaa'ikah|2:248|the Angels|ٱلۡ=al- مَ=ma لَٰٓ=laaaa ئِ='i كَ=ka ةُ=tu
    waqf|رَحۡمَةً|raHmatan|raHmah|3:8|mercy|رَحۡ=raH مَ=ma ةً=tan
    waqf|قَرۡيَةٍ|qaryatin|qaryah|2:259|a township|قَرۡ=qar يَ=ya ةٍ=tin
    waqf|وَٰحِدَةً|waaHidatan|waaHidah|2:213|single|وَٰ=waa حِ=Hi دَ=da ةً=tan
    waqf|أُمَّةً|ummatan|ummah|2:128|a community|أُ=u مَّ=mma ةً=tan
    waqf|ءَالِهَةً|aalihatan|aalihah|6:19|(there are) gods|ءَا=aa لِ=li هَ=ha ةً=tan
    waqf|وَرَحۡمَةً|waraHmatan|waraHmah|4:96|and mercy|وَ=wa رَحۡ=raH مَ=ma ةً=tan
    waqf|قَلِيلًا|qaliilan|qaliilaa|2:41|small|قَ=qa لِي=lii لًا=lan
    waqf|جَمِيعًا|jamiiʿan|jamiiʿaa|2:29|all|جَ=ja مِي=mii عًا=ʿan
    waqf|كَثِيرًا|kathiiran|kathiiraa|2:26|many|كَ=ka ثِي=thii رًا=ran
    waqf|قَوۡمًا|qawman|qawmaa|3:86|a people|قَوۡ=qaw مًا=man
    waqf|عَذَابًا|ʿadhaaban|ʿadhaabaa|3:56|(with) a punishment|عَ=ʿa ذَا=dhaa بًا=ban
    waqf|خَيۡرًا|khayran|khayraa|2:158|good|خَيۡ=khay رًا=ran
    waqf|صَٰلِحًا|SaaliHan|SaaliHaa|2:62|righteous deeds|صَٰ=Saa لِ=li حًا=Han
    waqf|سَبِيلًا|sabiilan|sabiilaa|3:97|(find) a way|سَ=sa بِي=bii لًا=lan
    waqf|أَبَدًا|abadan|abadaa|2:95|ever|أَ=a بَ=ba دًا=dan
    waqf|هُدًى|hudan|hudaa|2:2|a Guidance|هُ=hu دًى=dan
    waqf|شَيۡءٍ|shay'in|shay'|2:20|thing|شَيۡ=shay ءٍ='in
    waqf|عَلِيمٌ|ʿaliimun|ʿaliim|2:29|(is) All-Knowing|عَ=ʿa لِي=lii مٌ=mun
    waqf|خَيۡرٌ|khayrun|khayr|2:54|(is) better|خَيۡ=khay رٌ=run
    waqf|عَذَابٌ|ʿadhaabun|ʿadhaab|2:7|(is) a punishment|عَ=ʿa ذَا=dhaa بٌ=bun
    waqf|يَوۡمَئِذٍ|yawma'idhin|yawma'idh|3:167|that day|يَوۡ=yaw مَ=ma ئِ='i ذٍ=dhin
    waqf|غَفُورٌ|ghafuurun|ghafuur|2:173|(is) Oft-Forgiving|غَ=gha فُو=fuu رٌ=run
    waqf|أَلِيمٌ|aliimun|aliim|2:10|painful|أَ=a لِي=lii مٌ=mun
    waqf|قَدِيرٌ|qadiirun|qadiir|2:20|All-Powerful|قَ=qa دِي=dii رٌ=run
    waqf|بَعۡضٍ|baʿDin|baʿD|2:76|some (others)|بَعۡ=baʿ ضٍ=Din
    waqf|جَنَّٰتٍ|jannaatin|jannaat|2:25|(will be) Gardens|جَ=ja نَّٰ=nnaa تٍ=tin
    waqf|بِهِۦ|bihii|bih|2:22|therewith|بِ=bi هِۦ=hii
    waqf|لَهُۥ|lahuu|lah|2:102|for him|لَ=la هُۥ=huu
    waqf|إِنَّهُۥ|innahuu|innah|2:37|Indeed He|إِ=i نَّ=nna هُۥ=huu
    waqf|وَإِنَّهُۥ|wa'innahuu|wa'innah|2:130|and indeed he|وَ=wa إِ='i نَّ=nna هُۥ=huu
    waqf|دُونِهِۦ|duunihii|duunih|6:51|other than Him|دُو=duu نِ=ni هِۦ=hii
    waqf|رَبِّهِۦ|rabbihii|rabbih|2:112|his Lord|رَ=ra بِّ=bbi هِۦ=hii
    waqf|ٱللَّهِ|allaahi|allaah|1:1|(of) Allah|
    waqf|ٱلَّذِينَ|al-ladhiina|al-ladhiin|1:7|(of) those|ٱ=al- لَّ=la ذِي=dhii نَ=na
    waqf|ٱللَّهُ|allaahu|allaah|2:7|Allah|
    waqf|وَٱللَّهُ|wallaahu|wallaah|2:19|And Allah|
    waqf|ٱلۡأَرۡضِ|al-arDi|al-arD|2:11|the earth|ٱلۡ=al- أَرۡ=ar ضِ=Di
    waqf|ٱلسَّمَٰوَٰتِ|as-samaawaati|as-samaawaat|2:33|(of) the heavens|ٱل=as- سَّ=sa مَٰ=maa وَٰ=waa تِ=ti
    waqf|وَٱلَّذِينَ|wal-ladhiina|wal-ladhiin|2:4|And those who|وَٱ=wal- لَّ=la ذِي=dhii نَ=na
    waqf|عَلَيۡهِ|ʿalayhi|ʿalayh|2:37|towards him|عَ=ʿa لَيۡ=lay هِ=hi
    waqf|بِٱللَّهِ|billaahi|billaah|2:8|in Allah|
    waqf|أُوْلَٰٓئِكَ|ulaaaa'ika|ulaaaa'ik|2:5|Those|أُوْ=u لَٰٓ=laaaa ئِ='i كَ=ka
    waqf|يَشَآءُ|yashaaaa'u|yashaaaa'|2:90|He wills|يَ=ya شَآ=shaaaa ءُ='u
    waqf|وَٱلۡأَرۡضِ|wal-arDi|wal-arD|2:33|and the earth|وَٱلۡ=wal- أَرۡ=ar ضِ=Di
    waqf|ٱلنَّاسِ|an-naasi|an-naas|2:8|the people|ٱل=an- نَّا=naa سِ=si
    waqf|يُؤۡمِنُونَ|yu'minuuna|yu'minuun|2:3|believe|يُؤۡ=yu' مِ=mi نُو=nuu نَ=na
    waqf|وَقَالَ|waqaala|waqaal|2:118|And said|وَ=wa قَا=qaa لَ=la
    waqf|وَكَانَ|wakaana|wakaan|2:34|and became|وَ=wa كَا=kaa نَ=na
    waqf|كَذَٰلِكَ|kadhaalika|kadhaalik|2:73|Like this|كَ=ka ذَٰ=dhaa لِ=li كَ=ka
    waqf|تَعۡمَلُونَ|taʿmaluuna|taʿmaluun|2:74|you do|تَعۡ=taʿ مَ=ma لُو=luu نَ=na
    """

    /// ayah text | connected reading, stopped on the last word | surah:ayah | Saheeh International
    static let ayat = """
    بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ|bismi llaahi r-raHmaani r-raHiim|1:1|In the name of Allah, the Entirely Merciful, the Especially Merciful.
    ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ|al-Hamdu lillaahi rabbi l-ʿaalamiin|1:2|[All] praise is [due] to Allah, Lord of the worlds -
    ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ|ar-raHmaani r-raHiim|1:3|The Entirely Merciful, the Especially Merciful,
    مَٰلِكِ يَوۡمِ ٱلدِّينِ|maaliki yawmi d-diin|1:4|Sovereign of the Day of Recompense.
    إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ|iyyaaka naʿbudu wa'iyyaaka nastaʿiin|1:5|It is You we worship and You we ask for help.
    عَمَّ يَتَسَآءَلُونَ|ʿamma yatasaaaa'aluun|78:1|About what are they asking one another?
    أَلَمۡ نَجۡعَلِ ٱلۡأَرۡضَ مِهَٰدًا|alam najʿali l-arDa mihaadaa|78:6|Have We not made the earth a resting place?
    وَٱلۡجِبَالَ أَوۡتَادًا|wal-jibaala awtaadaa|78:7|And the mountains as stakes?
    وَخَلَقۡنَٰكُمۡ أَزۡوَٰجًا|wakhalaqnaakum azwaajaa|78:8|And We created you in pairs
    وَجَعَلۡنَا نَوۡمَكُمۡ سُبَاتًا|wajaʿalnaa nawmakum subaataa|78:9|And made your sleep [a means for] rest
    وَجَنَّٰتٍ أَلۡفَافًا|wajannaatin alfaafaa|78:16|And gardens of entwined growth.
    إِنَّ يَوۡمَ ٱلۡفَصۡلِ كَانَ مِيقَٰتًا|inna yawma l-faSli kaana miiqaataa|78:17|Indeed, the Day of Judgement is an appointed time -
    وَسُيِّرَتِ ٱلۡجِبَالُ فَكَانَتۡ سَرَابًا|wasuyyirati l-jibaalu fakaanat saraabaa|78:20|And the mountains are removed and will be [but] a mirage.
    إِنَّ جَهَنَّمَ كَانَتۡ مِرۡصَادًا|inna jahannama kaanat mirSaadaa|78:21|Indeed, Hell has been lying in wait
    إِنَّهُمۡ كَانُواْ لَا يَرۡجُونَ حِسَابًا|innahum kaanuu laa yarjuuna Hisaabaa|78:27|Indeed, they were not expecting an account
    وَكُلَّ شَيۡءٍ أَحۡصَيۡنَٰهُ كِتَٰبًا|wakulla shay'in aHSaynaahu kitaabaa|78:29|But all things We have enumerated in writing.
    إِنَّ لِلۡمُتَّقِينَ مَفَازًا|inna lilmuttaqiina mafaazaa|78:31|Indeed, for the righteous is attainment -
    حَدَآئِقَ وَأَعۡنَٰبًا|Hadaaaa'iqa wa'aʿnaabaa|78:32|Gardens and grapevines
    وَكَوَاعِبَ أَتۡرَابًا|wakawaaʿiba atraabaa|78:33|And full-breasted [companions] of equal age
    وَٱلنَّٰزِعَٰتِ غَرۡقًا|wan-naaziʿaati gharqaa|79:1|By those [angels] who extract with violence
    وَٱلنَّٰشِطَٰتِ نَشۡطًا|wan-naashiTaati nashTaa|79:2|And [by] those who remove with ease
    وَٱلسَّٰبِحَٰتِ سَبۡحًا|was-saabiHaati sabHaa|79:3|And [by] those who glide [as if] swimming
    فَٱلسَّٰبِقَٰتِ سَبۡقًا|fas-saabiqaati sabqaa|79:4|And those who race each other in a race
    فَٱلۡمُدَبِّرَٰتِ أَمۡرًا|fal-mudabbiraati amraa|79:5|And those who arrange [each] matter,
    يَوۡمَ تَرۡجُفُ ٱلرَّاجِفَةُ|yawma tarjufu r-raajifah|79:6|On the Day the blast [of the Horn] will convulse [creation],
    أَبۡصَٰرُهَا خَٰشِعَةٌ|abSaaruhaa khaashiʿah|79:9|Their eyes humbled.
    ٱذۡهَبۡ إِلَىٰ فِرۡعَوۡنَ إِنَّهُۥ طَغَىٰ|idhhab ilaa firʿawna innahuu Taghaa|79:17|"Go to Pharaoh. Indeed, he has transgressed.
    وَأَهۡدِيَكَ إِلَىٰ رَبِّكَ فَتَخۡشَىٰ|wa'ahdiyaka ilaa rabbika fatakhshaa|79:19|And let me guide you to your Lord so you would fear [Him]?'"
    فَكَذَّبَ وَعَصَىٰ|fakadhdhaba waʿaSaa|79:21|But Pharaoh denied and disobeyed.
    قَالَ أَنظِرۡنِيٓ إِلَىٰ يَوۡمِ يُبۡعَثُونَ|qaala anDhirniiii ilaa yawmi yubʿathuun|7:14|[Satan] said, "Reprieve me until the Day they are resurrected."
    وَرَفَعۡنَٰهُ مَكَانًا عَلِيًّا|warafaʿnaahu makaanan ʿaliyyaa|19:57|And We raised him to a high station.
    تِلۡكَ ءَايَٰتُ ٱلۡكِتَٰبِ ٱلۡمُبِينِ|tilka aayaatu l-kitaabi l-mubiin|26:2|These are the verses of the clear Book.
    ثُمَّ أَغۡرَقۡنَا بَعۡدُ ٱلۡبَاقِينَ|thumma aghraqnaa baʿdu l-baaqiin|26:120|Then We drowned thereafter the remaining ones.
    أَلَّا تَعۡلُواْ عَلَيَّ وَأۡتُونِي مُسۡلِمِينَ|allaa taʿluu ʿalayya wa'tuunii muslimiin|27:31|Be not haughty with me but come to me in submission [as Muslims].' "
    إِنَّهُمۡ أَلۡفَوۡاْ ءَابَآءَهُمۡ ضَآلِّينَ|innahum alfaw aabaaaa'ahum Daaaalliin|37:69|Indeed they found their fathers astray.
    فَتَوَلَّ عَنۡهُمۡ حَتَّىٰ حِينٍ|fatawalla ʿanhum Hattaa Hiin|37:174|So, [O Muhammad], leave them for a time.
    يَدۡعُونَ فِيهَا بِكُلِّ فَٰكِهَةٍ ءَامِنِينَ|yadʿuuna fiihaa bikulli faakihatin aaminiin|44:55|They will call therein for every [kind of] fruit - safe and secure.
    وَلَقَدۡ رَءَاهُ نَزۡلَةً أُخۡرَىٰ|walaqad ra'aahu nazlatan ukhraa|53:13|And he certainly saw him in another descent
    سَيُهۡزَمُ ٱلۡجَمۡعُ وَيُوَلُّونَ ٱلدُّبُرَ|sayuhzamu l-jamʿu wayuwalluuna d-dubur|54:45|[Their] assembly will be defeated, and they will turn their backs [in retreat].
    فَبِأَيِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ|fabi'ayyi aalaaaa'i rabbikumaa tukadhdhibaan|55:45|So which of the favors of your Lord would you deny?
    وَٱلسَّٰبِقُونَ ٱلسَّٰبِقُونَ|was-saabiquuna s-saabiquun|56:10|And the forerunners, the forerunners -
    بَلۡ نَحۡنُ مَحۡرُومُونَ|bal naHnu maHruumuun|68:27|Rather, we have been deprived."
    إِذَا مَسَّهُ ٱلشَّرُّ جَزُوعًا|idhaa massahu sh-sharru jazuuʿaa|70:20|When evil touches him, impatient,
    مَا سَلَكَكُمۡ فِي سَقَرَ|maa salakakum fii saqar|74:42|[And asking them], "What put you into Saqar?"
    """

    /// bare spelling | reading (stopped) | the same word with its marks | surah:ayah | gloss | sounded out
    static let unmarked = """
    إلا|illaa|إِلَّا|2:26|except|إِ=i لَّا=llaa
    قال|qaal|قَالَ|2:30|said|قَا=qaa لَ=la
    على|ʿalaa|عَلَىٰ|2:5|(are) on|عَ=ʿa لَىٰ=laa
    كان|kaan|كَانَ|2:75|(there) has been|كَا=kaa نَ=na
    فيها|fiihaa|فِيهَا|2:25|therein|فِي=fii هَا=haa
    إلى|ilaa|إِلَىٰ|2:14|with|إِ=i لَىٰ=laa
    إذا|idhaa|إِذَا|2:177|when|إِ=i ذَا=dhaa
    شيء|shay'|شَيۡءٍ|2:20|thing|شَيۡ=shay ءٍ='in
    عليه|ʿalayh|عَلَيۡهِ|2:37|towards him|عَ=ʿa لَيۡ=lay هِ=hi
    يوم|yawm|يَوۡمَ|2:113|(on the) Day|يَوۡ=yaw مَ=ma
    عليكم|ʿalaykum|عَلَيۡكُمۡ|2:40|upon you|عَ=ʿa لَيۡ=lay كُمۡ=kum
    إنا|innaa|إِنَّا|2:14|Indeed, we|إِ=i نَّا=nnaa
    الدنيا|ad-dunyaa|ٱلدُّنۡيَا|2:85|(of) the world|ٱل=ad- دُّنۡ=dun يَا=yaa
    حتى|Hattaa|حَتَّىٰ|2:55|until|حَ=Ha تَّىٰ=ttaa
    الناس|an-naas|ٱلنَّاسِ|2:8|the people|ٱل=an- نَّا=naa سِ=si
    إنما|innamaa|إِنَّمَا|2:11|Only|إِ=i نَّ=nna مَا=maa
    إني|innii|إِنِّي|2:30|Indeed, I (am)|إِ=i نِّي=nnii
    إليه|ilayh|إِلَيۡهِ|2:28|to Him|إِ=i لَيۡ=lay هِ=hi
    خير|khayr|خَيۡرٌ|2:54|(is) better|خَيۡ=khay رٌ=run
    دون|duun|دُونِ|2:23|other than|دُو=duu نِ=ni
    النار|an-naar|ٱلنَّارِ|2:39|(of) the Fire|ٱل=an- نَّا=naa رِ=ri
    يؤمنون|yu'minuun|يُؤۡمِنُونَ|2:3|believe|يُؤۡ=yu' مِ=mi نُو=nuu نَ=na
    بها|bihaa|بِهَا|2:258|it|بِ=bi هَا=haa
    سبيل|sabiil|سَبِيلِ|2:154|(the) way|سَ=sa بِي=bii لِ=li
    عذاب|ʿadhaab|عَذَابٌ|2:7|(is) a punishment|عَ=ʿa ذَا=dhaa بٌ=bun
    إليك|ilayk|إِلَيۡكَ|2:4|to you|إِ=i لَيۡ=lay كَ=ka
    موسى|muusaa|مُوسَىٰ|2:54|Musa|مُو=muu سَىٰ=saa
    كنا|kunnaa|كُنَّا|4:97|We were|كُ=ku نَّا=nnaa
    منها|minhaa|مِنۡهَا|2:25|therefrom|مِنۡ=min هَا=haa
    لنا|lanaa|لَنَا|2:61|for us|لَ=la نَا=naa
    كيف|kayf|كَيۡفَ|2:28|How|كَيۡ=kay فَ=fa
    عليك|ʿalayk|عَلَيۡكَ|2:252|to you|عَ=ʿa لَيۡ=lay كَ=ka
    العزيز|al-ʿaziiz|ٱلۡعَزِيزُ|2:129|the All-Mighty|ٱلۡ=al- عَ=ʿa زِي=zii زُ=zu
    مما|mimmaa|مِمَّا|2:36|from what|مِ=mi مَّا=mmaa
    جميعا|jamiiʿaa|جَمِيعًا|2:29|all|جَ=ja مِي=mii عًا=ʿan
    غير|ghayr|غَيۡرَ|2:59|other (than)|غَيۡ=ghay رَ=ra
    قليلا|qaliilaa|قَلِيلًا|2:41|small|قَ=qa لِي=lii لًا=lan
    ليس|lays|لَيۡسَ|2:198|Not is|لَيۡ=lay سَ=sa
    يعملون|yaʿmaluun|يَعۡمَلُونَ|2:96|they do|يَعۡ=yaʿ مَ=ma لُو=luu نَ=na
    يقول|yaquul|يَقُولُ|2:8|say|يَ=ya قُو=quu لُ=lu
    يقولون|yaquuluun|يَقُولُونَ|2:79|they say|يَ=ya قُو=quu لُو=luu نَ=na
    لها|lahaa|لَهَا|2:134|for it|لَ=la هَا=haa
    علينا|ʿalaynaa|عَلَيۡنَا|2:70|to us|عَ=ʿa لَيۡ=lay نَا=naa
    كثيرا|kathiiraa|كَثِيرًا|2:26|many|كَ=ka ثِي=thii رًا=ran
    أفلا|afalaa|أَفَلَا|2:44|Then, will not|أَ=a فَ=fa لَا=laa
    اليوم|al-yawm|ٱلۡيَوۡمَ|2:249|today|ٱلۡ=al- يَوۡ=yaw مَ=ma
    عما|ʿammaa|عَمَّا|2:74|of what|عَ=ʿa مَّا=mmaa
    خيرا|khayraa|خَيۡرًا|2:158|good|خَيۡ=khay رًا=ran
    قالت|qaalat|قَالَتۡ|3:36|she said|قَا=qaa لَتۡ=lat
    قوما|qawmaa|قَوۡمًا|3:86|a people|قَوۡ=qaw مًا=man
    يريد|yuriid|يُرِيدُ|2:185|Intends|يُ=yu رِي=rii دُ=du
    عنها|ʿanhaa|عَنۡهَا|2:36|from it|عَنۡ=ʿan هَا=haa
    كانت|kaanat|كَانَتۡ|2:94|is|كَا=kaa نَتۡ=nat
    قيل|qiil|قِيلَ|2:11|it is said|قِي=qii لَ=la
    حكيم|Hakiim|حَكِيمٌ|2:209|All-Wise|حَ=Ha كِي=kii مٌ=mun
    رسول|rasuul|رَسُولٌ|2:87|a Messenger|رَ=ra سُو=suu لٌ=lun
    القوم|al-qawm|ٱلۡقَوۡمِ|2:250|the people|ٱلۡ=al- قَوۡ=qaw مِ=mi
    عذابا|ʿadhaabaa|عَذَابًا|3:56|(with) a punishment|عَ=ʿa ذَا=dhaa بًا=ban
    أليم|aliim|أَلِيمٌ|2:10|painful|أَ=a لِي=lii مٌ=mun
    قدير|qadiir|قَدِيرٌ|2:20|All-Powerful|قَ=qa دِي=dii رٌ=run
    إليهم|ilayhim|إِلَيۡهِمۡ|3:77|at them|إِ=i لَيۡ=lay هِمۡ=him
    العذاب|al-ʿadhaab|ٱلۡعَذَابِ|2:49|torment|ٱلۡ=al- عَ=ʿa ذَا=dhaa بِ=bi
    حين|Hiin|حِينٍ|2:36|a period|حِي=Hii نٍ=nin
    حيث|Hayth|حَيۡثُ|2:35|(from) wherever|حَيۡ=Hay ثُ=thu
    """

    /// kind (surah, name) | bare spelling | with marks | the familiar English spelling | meaning
    static let names = """
    surah|الفاتحة|الفَاتِحَة|Al-Fatihah|The Opener
    surah|البقرة|البَقَرَة|Al-Baqarah|The Cow
    surah|آل عمران|آلِ عِمرَان|Ali 'Imran|Family of Imran
    surah|النساء|النِّسَاء|An-Nisa|The Women
    surah|المائدة|المَائِدَة|Al-Ma'idah|The Table Spread
    surah|الأنعام|الأَنعَام|Al-An'am|The Cattle
    surah|الأعراف|الأَعرَاف|Al-A'raf|The Heights
    surah|الأنفال|الأَنفَال|Al-Anfal|The Spoils of War
    surah|التوبة|التَّوبَة|At-Tawbah|The Repentance
    surah|يونس|يُونُس|Yunus|Jonah
    surah|هود|هُود|Hud|Hud
    surah|يوسف|يُوسُف|Yusuf|Joseph
    surah|الرعد|الرَّعد|Ar-Ra'd|The Thunder
    surah|إبراهيم|إِبرَاهِيم|Ibrahim|Abraham
    surah|الحجر|الحِجر|Al-Hijr|The Rocky Tract
    surah|النحل|النَّحل|An-Nahl|The Bee
    surah|الإسراء|الإِسرَاء|Al-Israa|The Night Journey
    surah|الكهف|الكَهف|Al-Kahf|The Cave
    surah|مريم|مَريَم|Maryam|Mary
    surah|طه|طه|Taha|Ta-Ha
    surah|الأنبياء|الأَنبِيَاء|Al-Anbya|The Prophets
    surah|الحج|الحَج|Al-Hajj|The Pilgrimage
    surah|المؤمنون|المُؤمِنُون|Al-Mu'minun|The Believers
    surah|النور|النُّور|An-Noor|The Light
    surah|الفرقان|الفُرقَان|Al-Furqan|The Criterion
    surah|الشعراء|الشُّعَرَاء|Ash-Shu'ara|The Poets
    surah|النمل|النَّمل|An-Naml|The Ant
    surah|القصص|القَصَص|Al-Qasas|The Stories
    surah|العنكبوت|العَنكَبُوت|Al-'Ankabut|The Spider
    surah|الروم|الرُّوم|Ar-Rum|The Romans
    surah|لقمان|لُقمَان|Luqman|Luqman
    surah|السجدة|السَّجدَة|As-Sajdah|The Prostration
    surah|الأحزاب|الأَحزَاب|Al-Ahzab|The Combined Forces
    surah|سبإ|سَبَإ|Saba|Sheba
    surah|فاطر|فَاطِر|Fatir|Originator
    surah|يس|يسٓ|Ya-Sin|Ya Sin
    surah|الصافات|الصَّافَّات|As-Saffat|Those who set the Ranks
    surah|ص|ص|Sad|The Letter "Saad"
    surah|الزمر|الزُّمَر|Az-Zumar|The Troops
    surah|غافر|غَافِر|Ghafir|The Forgiver
    surah|فصلت|فُصِّلَت|Fussilat|Explained in Detail
    surah|الشورى|الشُّورَى|Ash-Shuraa|The Consultation
    surah|الزخرف|الزُّخرُف|Az-Zukhruf|The Ornaments of Gold
    surah|الدخان|الدُّخَان|Ad-Dukhan|The Smoke
    surah|الجاثية|الجَاثِيَة|Al-Jathiyah|The Crouching
    surah|الأحقاف|الأَحقَاف|Al-Ahqaf|The Wind-Curved Sandhills
    surah|محمد|مُحَمَّد|Muhammad|Muhammad
    surah|الفتح|الفَتح|Al-Fath|The Victory
    surah|الحجرات|الحُجُرَات|Al-Hujurat|The Rooms
    surah|ق|ق|Qaf|The Letter "Qaf"
    surah|الذاريات|الذَّارِيَات|Adh-Dhariyat|The Winnowing Winds
    surah|الطور|الطُّور|At-Tur|The Mount
    surah|النجم|النَّجم|An-Najm|The Star
    surah|القمر|القَمَر|Al-Qamar|The Moon
    surah|الرحمن|الرَّحمَٰن|Ar-Rahman|The Beneficent
    surah|الواقعة|الوَاقِعَة|Al-Waqi'ah|The Inevitable
    surah|الحديد|الحَدِيد|Al-Hadid|The Iron
    surah|المجادلة|المُجَادِلَة|Al-Mujadila|The Pleading Woman
    surah|الحشر|الحَشر|Al-Hashr|The Exile
    surah|الممتحنة|المُمتَحَنَة|Al-Mumtahanah|She that is to be examined
    surah|الصف|الصَّف|As-Saf|The Ranks
    surah|الجمعة|الجُمُعَة|Al-Jumu'ah|The Congregation, Friday
    surah|المنافقون|المُنَافِقُون|Al-Munafiqun|The Hypocrites
    surah|التغابن|التَّغَابُن|At-Taghabun|The Mutual Disillusion
    surah|الطلاق|الطَّلَاق|At-Talaq|The Divorce
    surah|التحريم|التَّحرِيم|At-Tahrim|The Prohibition
    surah|الملك|المُلك|Al-Mulk|The Sovereignty
    surah|القلم|القَلَم|Al-Qalam|The Pen
    surah|الحاقة|الحَاقَّة|Al-Haqqah|The Reality
    surah|المعارج|المَعَارِج|Al-Ma'arij|The Ascending Stairways
    surah|نوح|نُوح|Nuh|Noah
    surah|الجن|الجِنّ|Al-Jinn|The Jinn
    surah|المزمل|المُزَّمِّل|Al-Muzzammil|The Enshrouded One
    surah|المدثر|المُدَّثِّر|Al-Muddaththir|The Cloaked One
    surah|القيامة|القِيَامَة|Al-Qiyamah|The Resurrection
    surah|الإنسان|الإِنسَان|Al-Insan|The Man
    surah|المرسلات|المُرسَلَات|Al-Mursalat|The Emissaries
    surah|النبإ|النَّبَإ|An-Naba|The Tidings
    surah|النازعات|النَّازِعَات|An-Nazi'at|Those who drag forth
    surah|عبس|عَبَس|'Abasa|He Frowned
    surah|التكوير|التَّكوِير|At-Takwir|The Overthrowing
    surah|الإنفطار|الإنفِطَار|Al-Infitar|The Cleaving
    surah|المطففين|المُطَفِّفِين|Al-Mutaffifin|The Defrauding
    surah|الإنشقاق|الإنشِقَاق|Al-Inshiqaq|The Sundering
    surah|البروج|البُرُوج|Al-Buruj|The Mansions of the Stars
    surah|الطارق|الطَّارِق|At-Tariq|The Nightcommer
    surah|الأعلى|الأَعلَى|Al-A'la|The Most High
    surah|الغاشية|الغَاشِية|Al-Ghashiyah|The Overwhelming
    surah|الفجر|الفَجر|Al-Fajr|The Dawn
    surah|البلد|البَلَد|Al-Balad|The City
    surah|الشمس|الشَّمس|Ash-Shams|The Sun
    surah|الليل|اللَّيل|Al-Layl|The Night
    surah|الضحى|الضُّحَى|Ad-Duhaa|The Morning Hours
    surah|الشرح|الشَّرح|Ash-Sharh|The Relief
    surah|التين|التِّين|At-Tin|The Fig
    surah|العلق|العَلَق|Al-'Alaq|The Clot
    surah|القدر|القَدر|Al-Qadr|The Power
    surah|البينة|البَيِّنَة|Al-Bayyinah|The Clear Proof
    surah|الزلزلة|الزَّلزَلَة|Az-Zalzalah|The Earthquake
    surah|العاديات|العَادِيَات|Al-'Adiyat|The Courser
    surah|القارعة|القَارِعَة|Al-Qari'ah|The Calamity
    surah|التكاثر|التَّكَاثُر|At-Takathur|The Rivalry in world increase
    surah|العصر|العَصر|Al-'Asr|The Declining Day
    surah|الهمزة|الهُمَزَة|Al-Humazah|The Traducer
    surah|الفيل|الفِيل|Al-Fil|The Elephant
    surah|قريش|قُرَيش|Quraysh|Quraysh
    surah|الماعون|المَاعُون|Al-Ma'un|The Small kindnesses
    surah|الكوثر|الكَوثَر|Al-Kawthar|The Abundance
    surah|الكافرون|الكَافِرُون|Al-Kafirun|The Disbelievers
    surah|النصر|النَّصر|An-Nasr|The Divine Support
    surah|المسد|المَسَد|Al-Masad|The Palm Fiber
    surah|الإخلاص|الإِخلَاص|Al-Ikhlas|The Sincerity
    surah|الفلق|الفَلَق|Al-Falaq|The Daybreak
    surah|الناس|النَّاس|An-Nas|Mankind
    name|الرحمن|الرَّحمَٰن|Ar-Rahman|The Entirely Merciful
    name|الرحيم|الرَّحِيم|Ar-Raheem|The Especially Merciful
    name|الملك|المَلِك|Al-Malik|The King
    name|القدوس|القُدُّوس|Al-Quddus|The Most Sacred
    name|السلام|السَّلَام|As-Salam|The Giver of Peace
    name|المومن|المُؤمِن|Al-Mumin|The Infuser of Faith
    name|المهيمن|المُهَيمِن|Al-Muhaymin|The Guardian
    name|العزيز|العَزِيز|Al-Aziz|The Mighty One
    name|الجبار|الجَبَّار|Al-Jabbar|The All Compelling
    name|المتكبر|المُتَكَبِّر|Al-Mutakabbir|The Dominant One
    name|الخالق|الخَالِق|Al-Khaliq|The Creator
    name|البارئ|البَارِئ|Al-Bari|The Evolver
    name|المصور|المُصَوِّر|Al-Musawwir|The Flawless Shaper
    name|الغفار|الغَفَّار|Al-Ghaffar|The Great Forgiver
    name|القهار|القَهَّار|Al-Qahhar|The All-Prevailing One
    name|الوهاب|الوَهَّاب|Al-Wahhab|The Supreme Bestower
    name|الرزاق|الرَّزَّاق|Ar-Razzaq|The Total Provider
    name|الفتاح|الفَتَّاح|Al-Fattah|The Opener
    name|العليم|العَلِيم|Al-Alim|The All-Knowing One
    name|القابض|القَابِض|Al-Qabid|The Restricting One
    name|الباسط|البَاسِط|Al-Basit|The Extender
    name|الخافض|الخَافِض|Al-Khafid|The Reducer
    name|الرافع|الرَّافِع|Ar-Rafi|The Elevating One
    name|المعز|المُعِزّ|Al-Mu'izz|The Honourer-Bestower
    name|المذل|المُذِلّ|Al-Mudhill|The Abaser
    name|السميع|السَّمِيع|As-Sami|The All-Hearer
    name|البصير|البَصِير|Al-Baseer|The All-Seeing
    name|الحكم|الحَكَم|Al-Hakam|The Impartial Judge
    name|العدل|العَدل|Al-Adl|The Embodiment of Justice
    name|اللطيف|اللَّطِيف|Al-Lateef|The Knower of Subtleties
    name|الخبير|الخَبِير|Al-Khabir|The All-Aware One
    name|الحليم|الحَلِيم|Al-Haleem|The Clement One
    name|العظيم|العَظِيم|Al-Azeem|The Magnificent One
    name|الغفور|الغَفُور|Al-Ghafoor|The All-Forgiving
    name|الشكور|الشَّكُور|Ash-Shakur|The Acknowledging One
    name|العلي|العَلِيّ|Al-Aliyy|The Sublime One
    name|الكبير|الكَبِير|Al-Kabeer|The Great One
    name|الحفيظ|الحَفِيظ|Al-Hafeez|The Guarding One
    name|المقيت|المُقِيت|Al-Muqeet|The Sustaining One
    name|الحسيب|الحَسِيب|Al-Haseeb|The Reckoning One
    name|الجليل|الجَلِيل|Al-Jaleel|The Majestic One
    name|الكريم|الكَرِيم|Al-Karim|The Bountiful One
    name|الرقيب|الرَّقِيب|Ar-Raqib|The Watchful One
    name|المجيب|المُجِيب|Al-Mujeeb|The Responding One
    name|الواسع|الوَاسِع|Al-Wasi|The All-Pervading One
    name|الحكيم|الحَكِيم|Al-Hakeem|The Wise One
    name|الودود|الوَدُود|Al-Wadud|The Loving One
    name|المجيد|المَجِيد|Al-Majeed|The Glorious One
    name|الباعث|البَاعِث|Al-Ba'ith|The Infuser of New Life
    name|الشهيد|الشَّهِيد|Ash-Shaheed|The All Observing Witness
    name|الحق|الحَقّ|Al-Haqq|The Embodiment of Truth
    name|الوكيل|الوَكِيل|Al-Wakeel|The Universal Trustee
    name|القوي|القَوِيّ|Al-Qawiyy|The Strong One
    name|المتين|المَتِين|Al-Matin|The Firm One
    name|الولي|الوَلِيّ|Al-Waliy|The Protecting Associate
    name|الحميد|الحَمِيد|Al-Hameed|The Sole-Laudable One
    name|المحصي|المُحصِي|Al-Muhsi|The All-Enumerating One
    name|المبدئ|المُبدِئ|Al-Mubdi|The Originator
    name|المعيد|المُعِيد|Al-Muid|The Restorer
    name|المحيي|المُحيِي|Al-Muhyi|The Maintainer of life
    name|المميت|المُمِيت|Al-Mumeet|The Inflictor of Death
    name|الحي|الحَيّ|Al-Hayy|The Eternally Living One
    name|القيوم|القَيُّوم|Al-Qayyum|The Self-Subsisting One
    name|الواجد|الوَاجِد|Al-Wajid|The Pointing One
    name|الماجد|المَاجِد|Al-Maajid|The All-Noble One
    name|الواحد|الوَاحِد|Al-Wahid|The Only One
    name|الاحد|الأَحَد|Al-Ahad|The Sole One
    name|الصمد|الصَّمَد|As-Samad|The Supreme Provider
    name|القادر|القَادِر|Al-Qadir|The All-Powerful
    name|المقتدر|المُقتَدِر|Al-Muqtadir|The All Authoritative One
    name|المقدم|المُقَدِّم|Al-Muqaddim|The Expediting One
    name|الموخر|المُؤَخِّر|Al-Muakhkhir|The Delayer
    name|الاول|الأَوَّل|Al-Awwal|The Very First
    name|الاخر|الآخِر|Al-Akhir|The Infinite Last One
    name|الظاهر|الظَّاهِر|Az-Zaahir|The Perceptible
    name|الباطن|البَاطِن|Al-Baatin|The Imperceptible
    name|الوالي|الوَالِي|Al-Wali|The Holder of Supreme Authority
    name|المتعال|المُتَعَال|Al-Mutaali|The Extremely Exalted One
    name|البر|البَرّ|Al-Barr|The Fountain-Head of Truth
    name|التواب|التَّوَاب|At-Tawwab|The Ever-Acceptor of Repentance
    name|المنتقم|المُنتَقِم|Al-Muntaqim|The Retaliator
    name|العفو|العَفُوّ|Al-Afuw|The Supreme Pardoner
    name|الرءوف|الرَّءُوف|Ar-Rauf|The Benign One
    name|مالك الملك|مَالِكُ المُلك|Malikul-Mulk|The Eternal Possessor of Sovereignty
    name|ذو الجلال والاكرام|ذُو الجَلَالِ وَالإِكرَام|Dhul-Jalaali-Wal-Ikram|The Possessor of Majesty and Honour
    name|المقسط|المُقسِط|Al-Muqsit|The Just One
    name|الجامع|الجَامِع|Al-Jami|The Assembler of Scattered Creations
    name|الغني|الغَنِيّ|Al-Ghaniy|The Self-Sufficient One
    name|المغني|المُغنِي|Al-Mughni|The Enricher
    name|المانع|المَانِع|Al-Mani|The Preventer
    name|الضار|الضَّارّ|Ad-Darr|The Distressor
    name|النافع|النَّافِع|An-Naafi|The Bestower of Benefits
    name|النور|النُّور|An-Noor|The Prime Light
    name|الهادي|الهَادِي|Al-Hadi|The Provider of Guidance
    name|البديع|البَدِيع|Al-Badi|The Unique One
    name|الباقي|البَاقِي|Al-Baaqi|The Ever Surviving One
    name|الوارث|الوَارِث|Al-Warith|The Eternal Inheritor
    name|الرشيد|الرَّشِيد|Ar-Rasheed|The Guide to Path of Rectitude
    name|الصبور|الصَّبُور|As-Sabur|The Extensively Enduring One
    """

    /// bare spelling | the familiar English spelling | meaning
    static let everyday = """
    بسم الله|Bismillah|In the name of Allah
    الحمد لله|Alhamdulillah|All praise is for Allah
    سبحان الله|Subhan Allah|Glory be to Allah
    الله أكبر|Allahu Akbar|Allah is the Greatest
    لا إله إلا الله|La ilaha illa Allah|There is no god but Allah
    أستغفر الله|Astaghfirullah|I seek Allah's forgiveness
    إن شاء الله|In sha Allah|If Allah wills
    ما شاء الله|Ma sha Allah|What Allah has willed
    السلام عليكم|As-salamu alaykum|Peace be upon you
    وعليكم السلام|Wa alaykum as-salam|And upon you be peace
    جزاك الله خيرا|Jazak Allahu khayran|May Allah reward you with good
    بارك الله فيك|Barak Allahu feek|May Allah bless you
    لا حول ولا قوة إلا بالله|La hawla wa la quwwata illa billah|There is no might or power except with Allah
    إنا لله وإنا إليه راجعون|Inna lillahi wa inna ilayhi raji'un|We belong to Allah, and to Him we return
    صلى الله عليه وسلم|Salla Allahu alayhi wa sallam|May Allah send blessings and peace upon him
    رضي الله عنه|Radi Allahu anhu|May Allah be pleased with him
    سبحان الله وبحمده|Subhan Allahi wa bihamdih|Glory and praise be to Allah
    سبحان الله العظيم|Subhan Allah al-Adheem|Glory be to Allah, the Magnificent
    سبحان ربي العظيم|Subhana Rabbiyal-Adheem|Glory be to my Lord, the Magnificent
    سبحان ربي الأعلى|Subhana Rabbiyal-A'la|Glory be to my Lord, the Most High
    ربنا ولك الحمد|Rabbana wa lakal-hamd|Our Lord, and to You is all praise
    سمع الله لمن حمده|Sami' Allahu liman hamidah|Allah hears the one who praises Him
    الله أعلم|Allahu a'lam|Allah knows best
    أعوذ بالله من الشيطان الرجيم|A'udhu billahi min ash-shaytan ir-rajeem|I seek refuge in Allah from Satan, the outcast
    حسبنا الله ونعم الوكيل|Hasbuna Allahu wa ni'mal-wakeel|Allah is enough for us, and the best to rely on
    اللهم صل على محمد|Allahumma salli ala Muhammad|O Allah, send blessings upon Muhammad
    يرحمك الله|Yarhamuk Allah|May Allah have mercy on you
    """
}
