#!/usr/bin/env python3
"""Build Resources/Data/Quran/SimilarAyahs.json.xz - the offline "Similar
Ayahs" pack behind the reader's related-verses sheet.

SOURCES (both bundled in the sibling Tilawa app, ported with permission)
------------------------------------------------------------------------
1. verified-similar-verses.json - qurani.ai's similar-ayah/quran-hafs corpus,
   fetched once by Tilawa's scripts/fetch-verified-similar-verses.mjs. Marked
   meta.complete, so an ayah absent from it verifiably has NO verified match
   (1,690 ayahs have matches; 4,546 have none). Rows carry matched spans.
2. similar-verses.json - generated by Tilawa's scripts/build-similar-verses.mjs
   (phrase-overlap over the Uthmani text + Quranic Corpus morphology), with
   human-readable reason labels ("Shared phrase", "Root HwT", topic names).
3. Resources/JSONs-Deprecated/QUL/matching-ayah.json - QUL's (qul.tarteel.ai)
   similar-ayah table: 1,162 ayahs, each match carrying the WORD RANGES of the
   shared wording in the matched ayah plus a 0-100 score. Most of its pairs are
   already above; what it adds is the spans (so the sheet can tint the shared
   words) and 657 pairs the other two sources lack, ranked by score.

WHY MERGE AT BUILD TIME
-----------------------
Tilawa layers these at runtime (verified first, generated fallback, online
last). This app is offline-only, so the layering happens HERE, once: per ayah,
verified matches ranked by their API score, then generated matches that aren't
already present, capped at MAX_MATCHES. The pack stores the final display
order; the Swift store never ranks, merges, or scores.

OUTPUT FORMAT
-------------
xz (like the other Data/Quran payloads) over:

    { "2:255": [ [42, 4, "<shared phrase>", 1],          <- verified row
                 [20, 110, "<shared phrase>", 0, ["Shared phrase","Root HwT"]],
                 [59, 22, "<shared phrase>", 0, ["Shared words"], [[3, 5]], 70],
                 ... ], ... }

    row = [targetSurah, targetAyah, sharedPhrase, verifiedFlag, labels?, spans?, score?]
    sharedPhrase may be "" (a verified row whose API entry carried no span).
    spans (0-based inclusive token ranges in the TARGET ayah, this app's own
    tokens) and score come from QUL and ride on any row QUL also lists.

RUN
---
    python3 Scripts/build_similar_ayahs.py [tilawa-root]

Defaults to ../Tilawa. Fails (writing nothing) if any referenced ayah does not
exist in this app's Quran, or if a source file is missing.
"""

from __future__ import annotations

import importlib.util
import json
import pathlib
import sys
import lzma


def xz_compress(body: bytes) -> bytes:
    """xz stream, preset 9e, dictionary no larger than the payload needs (the app decodes it with
    Apple's Compression framework, COMPRESSION_LZMA, which reads the xz container directly)."""
    dict_size = 1 << 16
    while dict_size < len(body) and dict_size < (1 << 26):
        dict_size <<= 1
    filters = [{"id": lzma.FILTER_LZMA2, "preset": 9 | lzma.PRESET_EXTREME, "dict_size": dict_size}]
    return lzma.compress(body, format=lzma.FORMAT_XZ, check=lzma.CHECK_CRC32, filters=filters)

ROOT = pathlib.Path(__file__).resolve().parent.parent
QURAN_JSON = ROOT / "Resources" / "JSONs-Deprecated" / "Quran.json"
QUL_MATCHING = ROOT / "Resources" / "JSONs-Deprecated" / "QUL" / "matching-ayah.json"
OUT = ROOT / "Resources" / "Data" / "Quran" / "SimilarAyahs.json.xz"
DEFAULT_TILAWA = ROOT.parent / "Tilawa"

MAX_MATCHES = 12
# A QUL-only pair this strong outranks the generated phrase-overlap rows (it carries real shared
# words with their spans); weaker ones queue behind them.
QUL_STRONG_SCORE = 60

_qul_spec = importlib.util.spec_from_file_location("build_qul_packs", ROOT / "Scripts" / "build_qul_packs.py")
_qul = importlib.util.module_from_spec(_qul_spec)
_qul_spec.loader.exec_module(_qul)


def ayah_counts() -> dict[int, int]:
    quran = json.loads(QURAN_JSON.read_text(encoding="utf-8"))
    return {s["id"]: len(s["ayahs"]) for s in quran}


def parse_key(key: str) -> tuple[int, int] | None:
    parts = key.split(":")
    if len(parts) != 2:
        return None
    try:
        return int(parts[0]), int(parts[1])
    except ValueError:
        return None


def main() -> None:
    tilawa = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TILAWA
    verified_path = tilawa / "assets" / "quran" / "verified-similar-verses.json"
    generated_path = tilawa / "assets" / "quran" / "similar-verses.json"
    for p in (verified_path, generated_path):
        if not p.exists():
            raise SystemExit(f"source not found: {p}")

    counts = ayah_counts()
    verified = json.loads(verified_path.read_text(encoding="utf-8"))
    generated = json.loads(generated_path.read_text(encoding="utf-8"))

    if not verified.get("meta", {}).get("complete"):
        raise SystemExit("verified corpus is not marked complete - refusing a partial build")

    def valid(surah: int, ayah: int) -> bool:
        return surah in counts and 1 <= ayah <= counts[surah]

    problems: list[str] = []
    packed: dict[str, list[list]] = {}
    verified_rows = generated_rows = 0

    if not QUL_MATCHING.exists():
        raise SystemExit(f"source not found: {QUL_MATCHING}")
    qul_matching = json.loads(QUL_MATCHING.read_text(encoding="utf-8"))
    order, texts = _qul.load_quran()
    positions = _qul.PositionMap(order, texts, _qul.upstream_words(tilawa))
    tokens_by_key = {key: texts[key].split() for key in order}
    qul_rows = 0

    all_keys = set(verified.get("ayahs", {})) | set(generated.get("ayahs", {})) | set(qul_matching)
    for key in all_keys:
        source = parse_key(key)
        if source is None or not valid(*source):
            problems.append(f"bad source key {key}")
            continue

        rows: list[list] = []
        seen: set[tuple[int, int]] = {source}  # never list an ayah as similar to itself

        # Verified first, in the corpus's own order (already score-ranked by the API).
        for entry in verified.get("ayahs", {}).get(key, []):
            target = parse_key(entry[0]) if entry else None
            if target is None or not valid(*target):
                problems.append(f"{key}: bad verified target {entry[:1]}")
                continue
            if target in seen:
                continue
            seen.add(target)
            spans = entry[4] if len(entry) > 4 and entry[4] else []
            phrase = spans[0][2] if spans and len(spans[0]) > 2 else ""
            rows.append([target[0], target[1], phrase, 1])

        # Generated fill: the `v` verse list, skipping targets the verified rows cover.
        for entry in generated.get("ayahs", {}).get(key, {}).get("v", []):
            if len(rows) >= MAX_MATCHES:
                break
            target = parse_key(entry[0]) if entry else None
            if target is None or not valid(*target):
                problems.append(f"{key}: bad generated target {entry[:1]}")
                continue
            if target in seen:
                continue
            seen.add(target)
            phrase = entry[1] or ""
            labels = [l for l in (entry[3] if len(entry) > 3 and entry[3] else []) if l]
            row: list = [target[0], target[1], phrase, 0]
            if labels:
                row.append(labels[:4])
            rows.append(row)

        # QUL: spans + score onto rows already listed, new rows for the pairs only it has.
        strong: list[list] = []
        weak: list[list] = []
        for entry in qul_matching.get(key, []):
            target = parse_key(entry.get("matched_ayah_key", ""))
            if target is None or not valid(*target):
                problems.append(f"{key}: bad QUL target {entry.get('matched_ayah_key')}")
                continue
            target_key = f"{target[0]}:{target[1]}"
            spans = []
            for pair in entry.get("match_words") or []:
                if len(pair) != 2:
                    continue
                span = positions.span(target_key, int(pair[0]), int(pair[1]))
                if span is not None and span not in spans:
                    spans.append(span)
            score = int(entry.get("score") or 0)
            existing = next((r for r in rows if (r[0], r[1]) == target), None)
            if existing is not None:
                if len(existing) == 4:
                    existing.append([])
                existing[4:] = [existing[4], spans, score]
                continue
            if target in seen or not spans:
                continue
            seen.add(target)
            target_tokens = tokens_by_key[target_key]
            phrase = " ".join(target_tokens[spans[0][0]:spans[0][1] + 1])
            row = [target[0], target[1], phrase, 0, ["Shared words"], spans, score]
            (strong if score >= QUL_STRONG_SCORE else weak).append(row)
        strong.sort(key=lambda r: -r[6])
        weak.sort(key=lambda r: -r[6])
        first_generated = next((i for i, r in enumerate(rows) if r[3] == 0), len(rows))
        rows[first_generated:first_generated] = strong
        rows.extend(weak)
        qul_rows += len(strong) + len(weak)

        if rows:
            packed[key] = rows[:MAX_MATCHES]
            verified_rows += sum(1 for r in rows[:MAX_MATCHES] if r[3] == 1)
            generated_rows += sum(1 for r in rows[:MAX_MATCHES] if r[3] == 0)

    if problems:
        print(f"FAILED: {len(problems)} problem(s)", file=sys.stderr)
        for line in problems[:20]:
            print(f"  {line}", file=sys.stderr)
        raise SystemExit(1)

    body = json.dumps(packed, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8")
    blob = xz_compress(body)
    OUT.write_bytes(blob)

    print(f"{len(packed)} ayahs with matches ({verified_rows} verified rows, {generated_rows} generated rows, {qul_rows} added by QUL before the cap)")
    print(f"{OUT.name}: {len(body):,} raw -> {len(blob):,} xz")


if __name__ == "__main__":
    main()
